// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
const $=id=>document.getElementById(id);let identity=null,polling=false;
const display=(id,text)=>$(id).textContent=text;
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(identity?{'X-Home-CSRF':identity.csrf}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(!r.ok){const error=Error(data.error??'Home is unavailable');error.status=r.status;throw error;}return data;}
const notice=error=>display('error',error.message);
function message(text){const item=document.createElement('article');item.textContent=text;$('messages').append(item);}
function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>Promise.resolve(fn()).catch(notice);return b;}
async function refresh(){const [health,actions]=await Promise.all([api('/health'),api('/actions')]);display('status',`${health.model} · ${health.busy?'working':'connected'}`);$('actions').replaceChildren();for(const action of actions.pending){const row=document.createElement('article');row.textContent=`${action.tool}: ${action.status}\n${action.arguments??''}`;if(identity.role==='owner')row.append(button('I reviewed this outcome',async()=>{await api('/actions/acknowledge',{action_id:action.id,outcome_reviewed:true});await refresh();}));$('actions').append(row);}if(identity.role==='owner'){const {clients}=await api('/clients');$('clients').replaceChildren();for(const client of clients.filter(c=>!c.revoked)){const row=document.createElement('div');row.textContent=`${client.name} · ${client.role} `;row.append(button('Revoke',async()=>{await api('/clients/revoke',{id:client.id});await start();}));$('clients').append(row);}}}
async function resume(){const id=sessionStorage.getItem('home-request');if(!id||polling)return;polling=true;$('send').disabled=true;try{while(sessionStorage.getItem('home-request')===id){const result=await api('/requests/'+encodeURIComponent(id));display('request-state',result.status);if(result.response){message(result.response.reply);sessionStorage.removeItem('home-request');break;}if(result.status==='interrupted'){message('The server stopped during this request. Review action outcomes before another change.');sessionStorage.removeItem('home-request');break;}await new Promise(r=>setTimeout(r,1200));}}catch(error){notice(error);}finally{polling=false;$('send').disabled=false;await refresh().catch(notice);}}
async function start(){try{identity=await api('/identity');$('pairing').hidden=true;$('home').hidden=false;$('owner').hidden=identity.role!=='owner';display('error','');await refresh();await resume();}catch(error){if(error.status!==401){notice(error);return;}identity=null;$('pairing').hidden=false;$('home').hidden=true;display('status','Pair this browser to your home');}}
$('pair').onsubmit=async e=>{e.preventDefault();try{await api('/pair',{...Object.fromEntries(new FormData(e.target)),kind:'browser'});e.target.elements.code.value='';await start();}catch(error){notice(error);}};
$('ask').onsubmit=async e=>{e.preventDefault();if(sessionStorage.getItem('home-request')){notice(Error('Retrieve the previous result before sending another request.'));await resume();return;}const prompt=e.target.elements.prompt.value;const request_id=crypto.randomUUID();let session_id=sessionStorage.getItem('home-session');if(!session_id){session_id=crypto.randomUUID();sessionStorage.setItem('home-session',session_id);}sessionStorage.setItem('home-request',request_id);message('You: '+prompt);display('error','');$('send').disabled=true;try{const result=await api('/ask',{request_id,session_id,prompt,async:true});if(result.status==='accepted'){e.target.reset();await resume();}else{message(result.reply);sessionStorage.removeItem('home-request');}}catch(error){if([400,401,403,409,413,415,429].includes(error.status)){sessionStorage.removeItem('home-request');notice(error);return;}notice(Error(error.message+' — use Refresh to retrieve the existing request; do not resend.'));}finally{$('send').disabled=false;}};
$('refresh').onclick=()=>start().catch(notice);$('stop').onclick=()=>api('/cancel',{}).then(()=>display('request-state','Stopping; check the outcome.')).catch(notice);
$('logout').onclick=()=>api('/logout',{}).then(()=>{sessionStorage.clear();$('messages').replaceChildren();return start();}).catch(notice);
$('invite').onsubmit=async e=>{e.preventDefault();try{const result=await api('/clients/invite',Object.fromEntries(new FormData(e.target)));display('code',result.code+' — expires in 10 minutes; share only with the intended person.');}catch(error){notice(error);}};
start();
