// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
// Actual private owner, rendered Context and scoped inspection; synthetic provider.
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {setTimeout as delay} from 'node:timers/promises';
import {harnessCdp} from './fixtures/harness-cdp.mjs';
import {PiConnection} from '../dist/client/src/socket.js';
import {localConnect} from '../dist/platform/src/transport.js';
const source=fileURLToPath(new URL('../',import.meta.url));
async function until(fn,label){const end=Date.now()+12000;let last;while(Date.now()<end){try{if(await fn())return;}catch(error){last=error;}await delay(30);}throw Error('Harness composition timeout: '+label+(last?' ('+last.message+')':''));}
test('rendered Context shows boundary coverage, drops stale payloads and preserves read-only authority',{skip:process.platform!=='linux',timeout:60000},async t=>{
 const profile=await mkdtemp(join(tmpdir(),'augmentor-context-chrome-'));let fixture,chrome,panel,owner,link,output='',stderr='';
 t.after(async()=>{owner?.close();panel?.close();for(const child of [chrome,fixture])if(child?.pid&&child.exitCode===null){const ended=once(child,'exit');child.kill('SIGTERM');await ended;}await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});});
 const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!/^(AUGMENTOR_|DSH_|PI_)/.test(key)));for(const key of ['AUGMENTOR_PI_TEST_ROOT','AUGMENTOR_PYTHON'])if(process.env[key])env[key]=process.env[key];
 fixture=spawn(process.execPath,[join(source,'scripts/harness-ui-proof.mjs')],{cwd:source,env:{...env,AUGMENTOR_HARNESS_PROOF_RECORD_REQUESTS:'1'},stdio:['ignore','pipe','pipe']});fixture.stdout.on('data',data=>output+=data);fixture.stderr.on('data',data=>stderr+=data);
 await until(()=>{assert.equal(fixture.exitCode,null,stderr);try{link=JSON.parse(output.trim().split('\n').find(line=>line.startsWith('{"fixture"')));return !!link;}catch{return false;}},'owner ready');
 const url=new URL(link.url),token=new URLSearchParams(url.hash.slice(1)).get('token');
 const rpc=async(method,params={},bearer=token)=>{const response=await fetch(url.origin+'/api/rpc',{method:'POST',headers:{Authorization:'Bearer '+bearer,'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),method,params})}),frame=await response.json();if(frame.error)throw Error(frame.error.message);return frame.result;};
 const socket=localConnect(join(link.state,'runtime.sock'));await once(socket,'connect');owner=new PiConnection(socket);await owner.call('host.hello',{protocol:'augmentor-pi/1'});
 chrome=spawn(process.env.CHROMIUM_BIN??'chromium',['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-first-run','--remote-debugging-port=0','--user-data-dir='+profile,link.url],{env,stdio:'ignore'});
 let port;await until(async()=>{try{port=(await readFile(join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];return true;}catch{return false;}},'Chrome ready');
 const target=(await fetch('http://127.0.0.1:'+port+'/json').then(r=>r.json())).find(row=>row.type==='page');panel=await harnessCdp(target.webSocketDebuggerUrl);for(const domain of ['Runtime','Log','Network','Page'])await panel.call(domain+'.enable');
 const visible=expression=>until(()=>panel.evaluate(expression),expression).catch(async error=>{error.message+=' '+JSON.stringify({body:await panel.evaluate('document.body.innerText'),errors:panel.errors,fixture:stderr});throw error;});
 const click=async expression=>{const point=await panel.evaluate('(()=>{const e='+expression+';if(!e||e.disabled)throw Error("Control unavailable");e.scrollIntoView({block:"nearest"});const r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;if(!r.width||!r.height||!e.contains(document.elementFromPoint(x,y)))throw Error("Control is not hit");return {x,y};})()');await panel.call('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',clickCount:1});await panel.call('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',clickCount:1});};
 await visible('!document.querySelector("#new-chat").disabled');await click('document.querySelector("#new-chat")');await visible('!document.querySelector("#send").disabled');const sid=await panel.evaluate('sessionStorage.getItem("augmentor-harness-session")');
 await click('document.querySelector("#input")');await panel.call('Input.insertText',{text:'CONTEXT_BOUNDARY_FIXTURE'});await visible('document.querySelector("#input").value==="CONTEXT_BOUNDARY_FIXTURE"');await click('document.querySelector("#send")');
 await visible('document.querySelector("#stop").disabled&&document.body.innerText.includes("The note says:")');
 const received=(await readFile(link.requestLog,'utf8')).trim().split('\n').map(line=>JSON.parse(line));assert.equal(received.length,2);
 const nativeFile=JSON.parse(await readFile(join(link.state,'sessions',sid+'.meta.json'),'utf8')).file,nativeOriginal=await readFile(nativeFile),displayFile=join(link.state,'sessions',sid+'.events.jsonl'),displayOriginal=await readFile(displayFile);
 const records=(await rpc('observation.list',{sessionId:sid})).records,requests=records.filter(row=>row.kind==='model/request'),lineages=records.filter(row=>row.kind==='context/provenance');assert.equal(lineages.length,2);assert.equal((await rpc('observation.describe')).capabilities.sourceProvenance,false);
 for(let i=0;i<2;i++){
  assert.equal(lineages[i].requestId,requests[i].id);
  let offset=0,text='';while(true){const page=await rpc('observation.payload',{sessionId:sid,eventId:lineages[i].id,offset});assert(page.available);text+=page.text;if(!page.hasMore)break;offset=page.nextOffset;}
  assert.deepEqual(JSON.parse(text).snapshots.afterProviderHooks,received[i]);
 }
 await click('document.querySelector("[data-view=context]")');await visible('document.querySelector("#context-content").innerText.includes("Context composition")&&document.querySelector("#context-content").innerText.includes("Complete source attribution is not yet available")&&document.querySelector("#context-content").innerText.includes("Provider body after payload hooks")');
 const choose=id=>panel.evaluate('(()=>{const e=document.querySelector("#requests");e.value='+JSON.stringify(id)+';e.dispatchEvent(new Event("change",{bubbles:true}));})()');
 await panel.evaluate('globalThis.__fetch=fetch;globalThis.__held=[];globalThis.fetch=(...args)=>__fetch(...args).then(response=>{let body;try{body=JSON.parse(args[1]?.body)}catch{}if(body?.method==="observation.payload"&&body.params.eventId==='+JSON.stringify(lineages[0].id)+')return new Promise(resolve=>__held.push(()=>resolve(response)));return response;})');
 await choose(requests[0].id);await visible('globalThis.__held.length>=1');await choose(requests[1].id);await visible('document.querySelector("#context-content").innerText.includes("Provider body after payload hooks")');
 const selected=await panel.evaluate('document.querySelector("#context-content").textContent');await panel.evaluate('globalThis.__held.splice(0).forEach(resolve=>resolve())');await delay(100);assert.equal(await panel.evaluate('document.querySelector("#context-content").textContent'),selected,'older request reply cannot repaint a new selection');
 await rpc('session.create',{sessionId:'context-foreign',selection:{provider:'fixture',model:'harness-fixture'},cwd:link.workspace});await rpc('session.rename',{sessionId:'context-foreign',title:'Foreign Context conversation'});
 await choose(requests[0].id);await visible('globalThis.__held.length>=1');await visible('Array.from(document.querySelectorAll(".session")).some(e=>e.textContent==="Foreign Context conversation")');await click('Array.from(document.querySelectorAll(".session")).find(e=>e.textContent==="Foreign Context conversation")');await visible('document.querySelector("#context-content > p").textContent==="No request is loaded for this conversation."&&document.querySelector(".native-history")&&!document.querySelector("#context-content details")');const empty=await panel.evaluate('document.querySelector("#context-content").textContent');
 await panel.evaluate('globalThis.__held.splice(0).forEach(resolve=>resolve())');await delay(100);assert.equal(await panel.evaluate('document.querySelector("#context-content").textContent'),empty);
 const inspection=await owner.call('inspection.open',{sessionId:sid}),inspectToken=new URLSearchParams(new URL(inspection.url).hash.slice(1)).get('token');
 // A same-origin hash navigation retains the operator document. The real
 // inspection entry point opens a fresh document; reload that URL here.
 await panel.call('Page.navigate',{url:inspection.url});await panel.reload();await visible('document.body.innerText.includes("Read-only")');await click('document.querySelector("[data-view=context]")');await visible('document.querySelector("#context-content").innerText.includes("Context composition")&&document.querySelector("#context-content").innerText.includes("Provider body after payload hooks")');
 await visible('document.querySelector(".native-history")?.innerText.includes("Read recorded source entry")');
 await panel.evaluate('(()=>{const select=document.querySelector(".native-history select");select.value=select.options[1].value;select.dispatchEvent(new Event("change"));})()');await click('Array.from(document.querySelectorAll(".native-history button")).find(e=>e.textContent==="Read recorded source entry")');await visible('document.querySelector(".native-entry-viewer").innerText.includes("Original entry")&&document.querySelector(".native-entry-viewer pre")');
 await click('Array.from(document.querySelectorAll(".native-history button")).find(e=>e.textContent==="Read saved Pi entries")');await visible('document.querySelectorAll(".native-history button[data-entry-id]").length>0');
 await click('Array.from(document.querySelectorAll(".native-history button[data-entry-id]")).find(e=>e.textContent.startsWith("toolResult"))');await visible('document.querySelector(".native-entry-viewer").innerText.includes("Harness fixture ready")&&document.querySelector(".native-entry-viewer").innerText.includes("Copy original entry")');
 const excerpt=await panel.evaluate('document.querySelector(".native-entry-viewer").textContent');await click('Array.from(document.querySelectorAll(".native-history button")).find(e=>e.textContent==="Recent entries")');await visible('!Array.from(document.querySelectorAll(".native-history button")).find(e=>e.textContent==="Read saved Pi entries").disabled');assert.equal(await panel.evaluate('document.querySelector(".native-entry-viewer").textContent'),excerpt,'paging keeps the selected original entry');
 assert.equal(await panel.evaluate('document.querySelector("#capture").disabled'),true);await assert.rejects(rpc('session.prompt',{sessionId:sid,requestId:'unauthorized',content:[{type:'text',text:'Must not execute'}]},inspectToken),/read-only/);await assert.rejects(rpc('observation.payload',{sessionId:'context-foreign',eventId:lineages[0].id},inspectToken),/selected conversation/);
 await assert.rejects(rpc('session.nativeRead',{sessionId:'context-foreign',entryId:'foreign'},inspectToken),/selected conversation/);await assert.rejects(rpc('session.nativeHistory',{sessionId:'context-foreign'},inspectToken),/selected conversation/);
 await assert.rejects(rpc('session.originalSearch',{sessionId:'context-foreign',query:'fixture'},inspectToken),/selected conversation/);await assert.rejects(rpc('session.originalRead',{sessionId:'context-foreign',source:'display',entryId:'1'},inspectToken),/selected conversation/);
 const setOriginal=async(query,scope)=>panel.evaluate('(()=>{const q=document.querySelector('+JSON.stringify('[aria-label="Search saved conversation originals"]')+'),s=document.querySelector('+JSON.stringify('[aria-label="Saved history search scope"]')+');q.value='+JSON.stringify(query)+';q.dispatchEvent(new Event("input"));s.value='+JSON.stringify(scope)+';s.dispatchEvent(new Event("change"));})()'),searchOriginal=()=>click('Array.from(document.querySelectorAll(".native-history button")).find(e=>e.textContent==="Search saved history")');
 await setOriginal('Harness fixture ready','selected-ancestry');await searchOriginal();await visible('document.querySelector(".original-search-results").innerText.includes("Harness fixture ready")&&document.querySelector(".original-search-status").innerText.includes("selected Pi ancestry")');await click('document.querySelector(".original-search-results button")');await visible('document.querySelector(".native-entry-viewer pre").innerText.includes("Harness fixture ready")');
 await setOriginal('Harness fixture ready','all-entries');await searchOriginal();await visible('document.querySelector(".original-search-status").innerText.includes("all saved Pi branches")&&document.querySelector(".original-search-results button")');
 await panel.evaluate('globalThis.__originalFetch=fetch;globalThis.__originalHeld=[];globalThis.fetch=(...args)=>__originalFetch(...args).then(response=>{let body;try{body=JSON.parse(args[1]?.body)}catch{}if(body?.method==="session.originalSearch"&&body.params.source==="pi")return new Promise(resolve=>__originalHeld.push(()=>resolve(response)));return response;})');
 await searchOriginal();await visible('globalThis.__originalHeld.length===1');await setOriginal('Harness fixture ready','display');await searchOriginal();await visible('document.querySelector(".original-search-status").innerText.includes("original display journal")&&document.querySelector(".original-search-results button[data-source=display]")');const displayResults=await panel.evaluate('document.querySelector(".original-search-results").textContent');await panel.evaluate('globalThis.__originalHeld.splice(0).forEach(resolve=>resolve())');await delay(100);assert.equal(await panel.evaluate('document.querySelector(".original-search-results").textContent'),displayResults,'delayed Pi results cannot repaint display originals');
 await click('document.querySelector(".original-search-results button")');await visible('document.querySelector(".native-entry-viewer").innerText.includes("Original display event")&&document.querySelector(".native-entry-viewer pre").innerText.includes("Harness fixture ready")');
 await panel.evaluate('globalThis.__originalHeld=[];globalThis.fetch=(...args)=>__originalFetch(...args).then(response=>{let body;try{body=JSON.parse(args[1]?.body)}catch{}if(body?.method==="session.originalRead")return new Promise(resolve=>__originalHeld.push(()=>resolve(response)));return response;})');await click('document.querySelector(".original-search-results button")');await visible('globalThis.__originalHeld.length===1');await setOriginal('a changed literal query','display');await visible('document.querySelector(".native-entry-viewer").innerText.includes("Pending original read cancelled")');const cancelled=await panel.evaluate('document.querySelector(".native-entry-viewer").textContent');await panel.evaluate('globalThis.__originalHeld.splice(0).forEach(resolve=>resolve());globalThis.fetch=__originalFetch');await delay(100);assert.equal(await panel.evaluate('document.querySelector(".native-entry-viewer").textContent'),cancelled,'changed query drops delayed original reads');
 await setOriginal('Harness fixture ready','display');await searchOriginal();await visible('document.querySelector(".original-search-status").innerText.includes("saved range complete")');
 await panel.call('Emulation.setDeviceMetricsOverride',{width:640,height:900,deviceScaleFactor:1,mobile:false});await visible('document.documentElement.scrollWidth<=640');await panel.evaluate('Array.from(document.querySelectorAll("#context-content h3")).find(e=>e.textContent==="Context composition").scrollIntoView({block:"start"})');await mkdir(join(source,'outputs/harness-proof'),{recursive:true});await writeFile(join(source,'outputs/harness-proof/context-composition.png'),Buffer.from((await panel.call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await panel.evaluate('document.querySelector(".native-history h3").scrollIntoView({block:"start"})');await writeFile(join(source,'outputs/harness-proof/native-history.png'),Buffer.from((await panel.call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await panel.evaluate('document.querySelector(".original-search-controls").scrollIntoView({block:"start"});new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');await visible('(()=>{const r=document.querySelector(".original-search-controls").getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight})()');await writeFile(join(source,'outputs/harness-proof/saved-original-search.png'),Buffer.from((await panel.call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await panel.reload();await visible('document.body.innerText.includes("Read-only")');await click('document.querySelector("[data-view=context]")');await visible('document.querySelector("#context-content").innerText.includes("Provider body after payload hooks")');
 const payloadMatches=await rpc('observation.search',{sessionId:sid,scope:'payloads',query:'Harness fixture ready'},inspectToken);assert(payloadMatches.coverage.scope==='retained-payloads-literal-search');await assert.rejects(rpc('observation.search',{sessionId:'context-foreign',scope:'all',query:'fixture'},inspectToken),/selected conversation/);
 await rpc('observation.clear',{sessionId:sid});await panel.reload();await visible('document.body.innerText.includes("Read-only")');await click('document.querySelector("[data-view=context]")');await visible('document.querySelector("#context-content > p").textContent==="No request is loaded for this conversation."&&document.querySelector(".native-history")');await click('Array.from(document.querySelectorAll(".native-history button")).find(e=>e.textContent==="Read saved Pi entries")');await visible('document.querySelectorAll(".native-history button[data-entry-id]").length>0');await click('Array.from(document.querySelectorAll(".native-history button[data-entry-id]")).find(e=>e.textContent.startsWith("toolResult"))');await visible('document.querySelector(".native-entry-viewer pre").innerText.includes("Harness fixture ready")');
 assert.equal((await readFile(link.requestLog,'utf8')).trim().split('\n').length,2,'selection, foreign read refusal, inspection and reload perform no inference');assert.deepEqual(panel.errors,[]);assert.deepEqual(panel.failedResponses,[]);assert.equal(stderr,'');
 assert.deepEqual(await readFile(nativeFile),nativeOriginal,'native inspection does not alter original saved entries');
 assert.deepEqual(await readFile(displayFile),displayOriginal,'raw original inspection does not compact or repair the display journal');
});
