// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash,createHmac} from 'node:crypto';
import {syncBuiltinESMExports} from 'node:module';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {SessionManager} from '@earendil-works/pi-coding-agent';
import {NativeHistory} from '../dist/runtime/src/native-history.js';
function fixture(t){const root=fs.mkdtempSync(join(tmpdir(),'augmentor-original-search-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return {root,file:join(root,'native.jsonl'),index:join(root,'derived','original'),manager:SessionManager.inMemory(root)};}
const message=text=>({role:'user',content:text,timestamp:Date.now()});
function save(f){fs.writeFileSync(f.file,[f.manager.getHeader(),...f.manager.getEntries()].map(row=>JSON.stringify(row)+'\n').join(''));}
function collect(reader,query,options={},cursor){const pages=[],entries=[];do{const page=reader.search({query,...options,...(cursor?{cursor}:{})});assert(page.available);pages.push(page);entries.push(...page.entries);cursor=page.nextCursor;if(!page.hasMore)break;assert(cursor);assert(pages.length<1000);}while(true);return {pages,entries};}
function collidingStamp(file,fn){const stat=fs.statSync,saved=stat(file,{bigint:true});fs.statSync=(path,...args)=>String(path)===file?saved:stat(path,...args);syncBuiltinESMExports();try{return fn();}finally{fs.statSync=stat;syncBuiltinESMExports();}}
test('v1 metadata rebuild preserves its signing key and accepts an original legacy page cursor without changing originals',t=>{
 const f=fixture(t),ids=[];for(let i=0;i<10;i++)ids.push(f.manager.appendMessage(message('AUTHORED_V1_ENTRY_'+i)));save(f);const original=fs.readFileSync(f.file),reader=new NativeHistory(f.file,f.index),first=reader.page({limit:2}),envelope=JSON.parse(fs.readFileSync(reader.manifest,'utf8')),key=envelope.value.key;
 const cursor=JSON.parse(Buffer.from(first.nextCursor.split('.')[0],'base64url').toString('utf8'));delete cursor.kind;const value=Buffer.from(JSON.stringify(cursor)).toString('base64url'),legacy=value+'.'+createHmac('sha256',Buffer.from(key,'hex')).update(value).digest('base64url');
 const rows=fs.readFileSync(reader.entries),oldRows=[];for(let at=0;at<rows.length;at+=272){const row=Buffer.alloc(240);rows.copy(row,0,at,at+232);createHash('sha256').update(row.subarray(0,232)).digest().copy(row,232,0,8);oldRows.push(row);}fs.writeFileSync(reader.entries,Buffer.concat(oldRows));envelope.value.version='augmentor-native-index/1';envelope.value.entries.size=oldRows.length*240;envelope.sha256=createHash('sha256').update(JSON.stringify(envelope.value)).digest('hex');fs.writeFileSync(reader.manifest,JSON.stringify(envelope));
 const upgraded=new NativeHistory(f.file,f.index),page=upgraded.page({limit:2,cursor:legacy});assert.deepEqual(page.entries.map(row=>row.entryId),ids.slice(6,8).reverse());const saved=JSON.parse(fs.readFileSync(reader.manifest,'utf8'));assert.equal(saved.value.version,'augmentor-native-index/2');assert.equal(saved.value.key,key);assert.equal(fs.statSync(reader.entries).size,10*272);assert.equal(upgraded.search({query:'AUTHORED_V1_ENTRY_0'}).coverage.indexBuildBytesRead,0);assert.deepEqual(fs.readFileSync(f.file),original);
});
test('Pi search distinguishes selected ancestry from all saved branches and finds edited-away originals',t=>{
 const f=fixture(t),a=f.manager.appendMessage(message('ROOT_SOURCE')),left=f.manager.appendMessage(message('LEFT_OLD_ORIGINAL'));f.manager.appendContextEdit(left,null);f.manager.branch(a);const right=f.manager.appendMessage(message('RIGHT_OTHER_BRANCH'));save(f);const original=fs.readFileSync(f.file),reader=new NativeHistory(f.file,f.index);
 assert.deepEqual(collect(reader,'LEFT_OLD_ORIGINAL',{leafId:right}).entries,[]);assert.deepEqual(collect(reader,'LEFT_OLD_ORIGINAL',{leafId:left}).entries.map(row=>row.entryId),[left]);assert.deepEqual(collect(reader,'LEFT_OLD_ORIGINAL',{scope:'all-entries'}).entries.map(row=>row.entryId),[left]);assert.deepEqual(collect(reader,'RIGHT_OTHER_BRANCH',{leafId:left}).entries,[]);
 const row=collect(reader,'LEFT_OLD_ORIGINAL',{scope:'all-entries'}).entries[0];assert(row.excerpt.text.includes('LEFT_OLD_ORIGINAL'));assert(reader.read(left,{entryHash:row.entryHash,pathHash:row.pathHash}).text.includes('LEFT_OLD_ORIGINAL'));assert.deepEqual(fs.readFileSync(f.file),original);assert.deepEqual(reader.search({query:'ROOT_SOURCE',leafId:null}).entries,[]);
});
test('authenticated selected/all-entry cursors retain their range across appends and refuse scope/query/source reuse',t=>{
 const f=fixture(t);for(let i=0;i<8;i++)f.manager.appendMessage(message('RANGE_MATCH '+i));save(f);const reader=new NativeHistory(f.file,f.index),first=reader.search({query:'RANGE_MATCH',scope:'all-entries',limit:2});assert(first.hasMore);const beforeIds=f.manager.getEntries().map(row=>row.id);f.manager.appendMessage(message('RANGE_MATCH FUTURE'));save(f);
 const rest=collect(reader,'RANGE_MATCH',{scope:'all-entries',limit:2},first.nextCursor);assert.deepEqual([...first.entries,...rest.entries].map(row=>row.entryId),beforeIds.reverse());assert.equal(collect(reader,'RANGE_MATCH',{scope:'all-entries'}).entries.length,9);
 assert.throws(()=>reader.search({query:'other',scope:'all-entries',cursor:first.nextCursor}),/query/);assert.throws(()=>reader.search({query:'RANGE_MATCH',scope:'selected-ancestry',cursor:first.nextCursor}),/scope/);assert.throws(()=>reader.search({query:'RANGE_MATCH',scope:'all-entries',nativeSessionId:'foreign'}),/identity/);assert.throws(()=>reader.page({cursor:first.nextCursor}),/cursor/);
 const nativePage=reader.page({limit:2});assert.throws(()=>reader.search({query:'RANGE_MATCH',cursor:nativePage.nextCursor}),/cursor/);const foreign=new NativeHistory(f.file,join(f.root,'other','index'));assert.throws(()=>foreign.search({query:'RANGE_MATCH',scope:'all-entries',cursor:first.nextCursor}),/cursor/);
 for(const args of [{query:''},{query:'x'.repeat(257)},{query:Array(17).fill('x').join(' ')},{query:'x',scope:'other'},{query:'x',limit:101}])assert.throws(()=>reader.search(args));
});
test('all-entry prefix identity detects an unrelated branch rewrite while unchanged selected ancestry remains usable',t=>{
 const f=fixture(t),root=f.manager.appendMessage(message('ROOT_MATCH')),other=f.manager.appendMessage(message('OTHER_MATCH'));f.manager.branch(root);for(let i=0;i<4;i++)f.manager.appendMessage(message('SELECTED_MATCH '+i));save(f);const reader=new NativeHistory(f.file,f.index),all=reader.search({query:'MATCH',scope:'all-entries',limit:1}),selected=reader.search({query:'MATCH',limit:1});
 collidingStamp(f.file,()=>{fs.writeFileSync(f.file,fs.readFileSync(f.file,'utf8').replace('OTHER_MATCH','ALTER_MATCH'));assert.throws(()=>reader.search({query:'MATCH',scope:'all-entries',cursor:all.nextCursor}),/range changed/);const unchanged=collect(reader,'MATCH',{},selected.nextCursor);assert.equal(unchanged.entries.length,4);assert(!unchanged.entries.some(row=>row.entryId===other));});
});
test('multi-megabyte split Unicode/far-apart terms resume after reopening with bounded verified source reads',t=>{
 const f=fixture(t),content='START_TERM '+ 'x'.repeat(65500)+'😀日本語 ΟΣ '+ 'z'.repeat(3*1024*1024)+' END_TERM',id=f.manager.appendMessage(message(content));save(f);const reader=new NativeHistory(f.file,f.index),original=fs.readFileSync(f.file),first=reader.search({query:'START_TERM 😀日本語 ος END_TERM'});assert(first.coverage.partialEntry);assert(first.hasMore);assert.deepEqual(first.entries,[]);assert(first.coverage.sourceBytesRead<=512*1024);
 const readFile=fs.readFileSync;fs.readFileSync=(path,...args)=>{assert.notEqual(String(path),f.file);return readFile(path,...args);};syncBuiltinESMExports();let rest;try{rest=collect(new NativeHistory(f.file,f.index),'START_TERM 😀日本語 ος END_TERM',{},first.nextCursor);}finally{fs.readFileSync=readFile;syncBuiltinESMExports();}
 assert.deepEqual(rest.entries.map(row=>row.entryId),[id]);assert(rest.pages.length>1);assert(rest.pages.every(page=>page.coverage.sourceBytesRead<=512*1024));assert(rest.entries[0].excerpt.text.includes('END_TERM'));assert.deepEqual(fs.readFileSync(f.file),original);
});
test('raw display search includes finalized-away deltas and original submissions without creating Pi context or repairing tails',t=>{
 const f=fixture(t),events=[{seq:1,type:'user/message',data:{content:[{type:'text',text:'ORIGINAL_TYPED_SUBMISSION'}]}},{seq:2,type:'assistant/chunk',data:{chunk:{type:'text-delta',text:'FINALIZED_AWAY_FRAGMENT'}}},{seq:3,type:'assistant/message',data:{message:{content:[{type:'text',text:'FINAL_VISIBLE_REPLY'}]}}},{seq:4,type:'runtime/notice',data:{message:'SAVED_UNKNOWN_OUTCOME'}}];fs.writeFileSync(f.file,events.map(row=>JSON.stringify(row)+'\n').join('')+'{"seq":5,"unfinished":');const original=fs.readFileSync(f.file),reader=new NativeHistory(f.file,f.index,'display-fixture');
 for(const [term,seq] of [['ORIGINAL_TYPED_SUBMISSION',1],['FINALIZED_AWAY_FRAGMENT',2],['SAVED_UNKNOWN_OUTCOME',4]]){const row=collect(reader,term,{scope:'all-entries'}).entries[0];assert.equal(row.sequence,seq);assert.equal(row.source,'display');assert.equal(row.time,undefined);assert.deepEqual(JSON.parse(reader.read(row.entryId,{entryHash:row.entryHash,pathHash:row.pathHash}).text),events[seq-1]);}
 const page=reader.search({query:'no-match',scope:'all-entries'});assert(page.coverage.incompleteTailBytes>0);assert.equal(page.coverage.effectiveProviderInput,false);assert.deepEqual(fs.readFileSync(f.file),original);assert.throws(()=>reader.search({query:'typed',scope:'selected-ancestry'}),/scope/);
 fs.writeFileSync(f.file,'');assert.deepEqual(new NativeHistory(f.file,f.index,'display-fixture').search({query:'absent',scope:'all-entries'}).entries,[]);
});
test('sparse searches advance beyond 1,000 entries and corruption or invalid display formats preserve originals',t=>{
 const f=fixture(t);for(let i=0;i<1200;i++)f.manager.appendMessage(message('SEARCH_SOURCE '+i));save(f);const reader=new NativeHistory(f.file,f.index),first=reader.search({query:'absent',scope:'all-entries'});assert(first.hasMore);assert.equal(first.coverage.completedRecords,1000);const last=reader.search({query:'absent',scope:'all-entries',cursor:first.nextCursor});assert(!last.hasMore);assert.equal(last.coverage.completedRecords,200);assert.deepEqual(collect(reader,'(?=SEARCH_SOURCE)').entries,[]);
 for(const source of ['{"seq":1,"type":"message","data":{}}\ninvalid\n','{"seq":2,"type":"message","data":{}}\n{"seq":1,"type":"message","data":{}}\n']){fs.writeFileSync(f.file,source);assert.throws(()=>new NativeHistory(f.file,f.index,'display-fixture').search({query:'x',scope:'all-entries'}),/Corrupt display/);assert.equal(fs.readFileSync(f.file,'utf8'),source);}
});
test('a modified middle block refuses an in-progress recorded search even with colliding source stamps',t=>{
 const f=fixture(t);f.manager.appendMessage(message('START_TERM '+ 'x'.repeat(2*1024*1024)+' END_TERM'));save(f);const reader=new NativeHistory(f.file,f.index),first=reader.search({query:'START_TERM END_TERM'});assert(first.coverage.partialEntry);collidingStamp(f.file,()=>{const fd=fs.openSync(f.file,'r+');try{fs.writeSync(fd,Buffer.from('y'),0,1,1048576);}finally{fs.closeSync(fd);}const bytes=fs.readFileSync(f.file);assert.throws(()=>collect(reader,'START_TERM END_TERM',{},first.nextCursor),/range changed/);assert.deepEqual(fs.readFileSync(f.file),bytes);});
});
