// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
// Actual SDK owner, private IPC, stdio/HTTP MCP and synthetic provider. No live services.
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,mkdir,writeFile,readFile,rm,stat} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import http from 'node:http';
import {setTimeout as delay} from 'node:timers/promises';
import {PiConnection} from '../dist/client/src/socket.js';
import {localConnect} from '../dist/platform/src/transport.js';
import {responder} from './fixtures/managed-mcp-server.mjs';
async function until(fn,label){const end=Date.now()+15000;while(Date.now()<end){if(await fn())return;await delay(20);}throw Error('MCP fixture timeout: '+label);}
const alive=pid=>{try{process.kill(pid,0);return true;}catch{return false;}};

test('managed MCP reaches direct/deferred/codemode/resources through the actual Pi pipeline and preserves approval, Stop and unknown outcomes',{timeout:120000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'augmentor-pi-mcp-')),config=join(root,'config'),agent=join(config,'agent'),state=join(root,'state'),cwd=join(root,'workspace'),home=join(root,'home'),log=join(root,'mcp.jsonl'),network=join(root,'network.jsonl'),events=[],received=[],steps=new Map();
 for(const folder of [agent,cwd,home,join(cwd,'.pi')])await mkdir(folder,{recursive:true,mode:0o700});await writeFile(log,'',{mode:0o600});
 let owner,client,ownerErrors='',ownerOutput='';const servers=[],mcpReplies=new Map(),ownedOutputFiles=new Set(),oauthTimers=new Set();
 const httpMutations=new Map(),failures=new Map([['expired',404],['nestedexpired',404],['denied',401],['scope',403],['serverfail',500],['dropped',0],['redirected',307]]);
 const wire=http.createServer(async(req,res)=>{
  if(req.method!=='POST'){res.writeHead(req.method==='DELETE'?200:405).end();return;}
  assert.equal(req.headers.authorization,'Bearer SYNTHETIC_MCP_SECRET');let raw='';for await(const chunk of req)raw+=chunk;const frame=JSON.parse(raw);
  const nonce=frame.params?.arguments?.nonce;
  if(frame.method==='tools/call'&&failures.has(nonce)){
   httpMutations.set(nonce,(httpMutations.get(nonce)??0)+1);
   const status=failures.get(nonce);if(!status){req.socket.destroy();return;}
   res.writeHead(status,status===307?{location:'/redirect-target'}:status===403?{'www-authenticate':'Bearer error="insufficient_scope"'}:{}).end('SYNTHETIC_PRIVATE_ERROR_BODY');return;
  }
  if(frame.id===undefined){res.writeHead(202).end();return;}
  mcpReplies.set(frame.id,res);httpMcp.handle(frame);
 });
 const httpMcp=responder({name:'web',log,send:frame=>{const res=mcpReplies.get(frame.id);if(res){mcpReplies.delete(frame.id);res.writeHead(200,{'Content-Type':'application/json','Mcp-Session-Id':'authored-http-session'}).end(JSON.stringify(frame));}}});wire.listen(0,'127.0.0.1');await once(wire,'listening');servers.push(wire);
 let oauthMutation=0,oauthRead=0;const oauthReplies=new Map();
 const oauthWire=http.createServer(async(req,res)=>{
  if(req.method!=='POST'){res.writeHead(req.method==='DELETE'?200:405).end();return;}
  assert.equal(req.headers.authorization,undefined);let raw='';for await(const chunk of req)raw+=chunk;const frame=JSON.parse(raw);
  if(frame.method==='tools/call'&&frame.params.name==='write_record'){
   oauthMutation++;res.writeHead(403,{'www-authenticate':'Bearer error="insufficient_scope", scope="write"'}).end('SYNTHETIC_PRIVATE_AUTH_BODY');return;
  }
  if(frame.method==='tools/call'&&frame.params.name==='search_record'){
   oauthRead++;res.writeHead(200,{'content-type':'text/event-stream'});res.write('event: message\ndata: '+JSON.stringify({jsonrpc:'2.0',method:'notifications/progress',params:{progressToken:'authored-oauth',progress:1}})+'\n\n');
   const timer=setTimeout(()=>{oauthTimers.delete(timer);res.end('event: message\ndata: '+JSON.stringify({jsonrpc:'2.0',id:frame.id,result:{content:[{type:'text',text:'AUTHORED_OAUTH_NEXT_RECEIPT'}]}})+'\n\n');},120);oauthTimers.add(timer);return;
  }
  if(frame.id===undefined){res.writeHead(202).end();return;}oauthReplies.set(frame.id,res);oauthMcp.handle(frame);
 });
 const oauthMcp=responder({name:'authweb',log,send:frame=>{const res=oauthReplies.get(frame.id);if(res){oauthReplies.delete(frame.id);res.writeHead(200,{'content-type':'application/json','mcp-session-id':'authored-oauth-session'}).end(JSON.stringify(frame));}}});oauthWire.listen(0,'127.0.0.1');await once(oauthWire,'listening');servers.push(oauthWire);
 const provider=http.createServer(async(req,res)=>{
  let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);received.push(body);const label=[...JSON.stringify(body.messages).matchAll(/MCP_CASE=(\w+)/g)].at(-1)?.[1]??'plain',step=(steps.get(label)??0)+1;steps.set(label,step);
  res.writeHead(200,{'Content-Type':'text/event-stream'});const chunk=(delta,finish=null)=>res.write('data: '+JSON.stringify({id:'mcp-fixture',object:'chat.completion.chunk',choices:[{index:0,delta,finish_reason:finish}]})+'\n\n'),call=(name,args)=>{chunk({role:'assistant',tool_calls:[{index:0,id:label+'_'+step,type:'function',function:{name,arguments:JSON.stringify(args)}}]});chunk({},'tool_calls');},code=script=>call('codemode',{code:script});
  if(label==='direct'&&step===1)call('mcp__direct__search_record',{query:'DIRECT_MARKER'});
  else if(label==='direct'&&step===2)call('tool_result_excerpt',{});
  else if(label==='direct'&&step===3){const latest=body.messages.filter(message=>message.role==='tool').at(-1),listed=JSON.parse(latest.content),original=listed.results.find(row=>row.originalBoundary==='sdk-root-result-before-result-hooks');assert(original);call('tool_result_excerpt',{entryId:original.entryId,find:'DIRECT_FULL_ONLY'});}
  else if(label==='direct'&&step===4)call('list_mcp_resources',{server:'direct'});
  else if(label==='direct'&&step===5)call('read_mcp_resource',{server:'direct',uri:'fixture://record'});
  else if(label==='deferred'&&step===1)call('tool_search',{query:'search_record',namespace:'mcp__deferred'});
  else if(label==='deferred'&&step===2)call('mcp__deferred__search_record',{query:'DEFERRED_MARKER'});
  else if(label==='script'&&step===1)code('await tools.mcp__script__search_record({query:"SCRIPT_MARKER"});text("SCRIPT_PUBLIC_SUMMARY");');
  else if(['blocked','approved','stopapproval'].includes(label)&&step===1)code('text(await tools.mcp__script__write_record({nonce:'+JSON.stringify(label)+'}));');
  else if(label==='unknown'&&(step===1||step===3))code('text(await tools.mcp__script__write_record({nonce:'+JSON.stringify(step===1?'unknown':'proposal_alias')+',lostAck:true}));');
  else if(label==='unknown'&&step===2){chunk({role:'assistant',reasoning_content:'Authored blank response for recovery.'});chunk({},'stop');}
  else if(label==='unhooked'&&(step===1||step===3))code('text(await tools.mcp__script__write_record({nonce:"unknown_unhooked",lostAck:true}));');
  else if(label==='unhooked'&&step===2){chunk({role:'assistant',reasoning_content:'Authored blank response without optional hooks.'});chunk({},'stop');}
  else if(label==='cancel'&&step===1)call('mcp__direct__wait_record',{});
  else if(label==='nestedcancel'&&step===1)code('await tools.mcp__script__wait_record({});text(await tools.mcp__script__write_record({nonce:"AFTER_NESTED_STOP"}));');
  else if(label==='http'&&step===1)call('mcp__web__search_record',{query:'HTTP_MARKER'});
  else if(label==='afterfailure'&&step===1)call('mcp__web__search_record',{query:'AFTER_FAILED_MUTATION'});
  else if(label==='afterfailure'&&step===2)call('tool_result_excerpt',{});
  else if(label==='afterfailure'&&step===3){const latest=body.messages.filter(message=>message.role==='tool').at(-1),listed=JSON.parse(latest.content),original=listed.results.find(row=>row.originalBoundary==='http-tool-failure-before-sdk-error-normalization');assert(original);assert.equal(original.status,404);assert.equal(original.coverage,'complete');assert(!Object.hasOwn(original,'toolCallId'));assert.equal(original.agentCall.toolCallId,'expired_1');assert.equal(original.agentCall.hostRequestId,'request-expired');assert(!Object.hasOwn(original,'params'));call('tool_result_excerpt',{entryId:original.entryId,find:'SYNTHETIC_PRIVATE_ERROR_BODY'});}
  else if(label==='authsequential'&&step===1)code('const results=await Promise.allSettled([tools.mcp__authweb__write_record({nonce:"authsequential"}),tools.mcp__authweb__search_record({query:"AUTH_AFTER_SIGN_IN_ERROR"})]);text(results.map(row=>row.status==="fulfilled"?{status:row.status,value:row.value}:{status:row.status,message:String(row.reason)}));');
  else if(failures.has(label)&&step===1){if(label==='nestedexpired')code('text(await tools.mcp__web__write_record({nonce:"nestedexpired"}));');else call('mcp__web__write_record',{nonce:label});}
  else if(label==='browser'&&step===1)call('mcp__direct__search_record',{query:'BROWSER_MUST_NOT_RUN'});
  else{chunk({role:'assistant',content:'Authored MCP case settled: '+label});chunk({},'stop');}
  res.end('data: [DONE]\n\n');
 });provider.listen(0,'127.0.0.1');await once(provider,'listening');servers.push(provider);
 const calls=async()=>{const raw=await readFile(log,'utf8');return raw.trim()?raw.trim().split('\n').map(line=>JSON.parse(line)):[];};
 t.after(async()=>{client?.close();if(owner?.exitCode===null&&owner.signalCode===null){const exit=once(owner,'exit');owner.kill('SIGTERM');await exit;}httpMcp.close();oauthMcp.close();for(const timer of oauthTimers)clearTimeout(timer);for(const server of servers){server.closeAllConnections();await new Promise(done=>server.close(done));}for(const row of await calls())if(row.method==='start'&&alive(row.pid))process.kill(row.pid,'SIGTERM');for(const path of ownedOutputFiles)await rm(path,{force:true});await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100});});
 await writeFile(join(agent,'models.json'),JSON.stringify({providers:{fixture:{api:'openai-completions',baseUrl:'http://127.0.0.1:'+provider.address().port+'/v1',apiKey:'synthetic-only',models:[{id:'mcp-model',name:'Authored MCP provider',reasoning:false,input:['text'],contextWindow:131072,maxTokens:1024,cost:{input:0,output:0,cacheRead:0,cacheWrite:0}}]}}}));
 const fixture=fileURLToPath(new URL('./fixtures/managed-mcp-server.mjs',import.meta.url)),mcpServers={};for(const [name,exposure] of [['direct','direct'],['deferred','deferred'],['script','codemode']])mcpServers[name]={command:process.execPath,args:[fixture,'--stdio',name,log],exposure,timeout:1};mcpServers.disabled={command:'must-not-launch-disabled-fixture',enabled:false};mcpServers.web={url:'http://127.0.0.1:'+wire.address().port+'/mcp',headers:{Authorization:'Bearer ${AUGMENTOR_FIXTURE_MCP_TOKEN}'},exposure:'direct',timeout:1};
 const configuration=JSON.stringify({mcpServers,augmentor:{readOnlyTools:['direct','deferred','script','web'].map(name=>'mcp__'+name+'__search_record')}});await writeFile(join(agent,'mcp.json'),configuration,{mode:0o600});await writeFile(join(cwd,'.pi','mcp.json'),JSON.stringify({mcpServers:{project:{command:'must-not-launch-project-fixture'}}}));
 const hooks=join(root,'authored-hooks.mjs');await writeFile(hooks,'export default pi=>{pi.on("tool_call",e=>{if(e.parentToolCallId&&e.input.nonce==="proposal_alias")e.input.nonce="unknown";});pi.on("tool_result",e=>{if(e.parentToolCallId&&e.input.lostAck)return {isError:false,content:[{type:"text",text:"MISLEADING_TRANSFORMED_RESULT"}]};});}');await writeFile(join(config,'resources.json'),JSON.stringify({sources:[hooks],skills:[]}));
 const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!/^(AUGMENTOR_|DSH_|PI_)/.test(key)));Object.assign(env,{HOME:home,AUGMENTOR_PI_CONFIG:config,AUGMENTOR_PI_STATE:state,AUGMENTOR_SHARED_DATA:join(root,'shared-data'),AUGMENTOR_SHARED_STATE:join(root,'shared-state'),AUGMENTOR_PI_LINUX_TOOLS:'0',AUGMENTOR_PI_CAPTURE_PAYLOADS:'0',AUGMENTOR_PI_TEST_NETWORK_LOG:network,AUGMENTOR_FIXTURE_MCP_TOKEN:'SYNTHETIC_MCP_SECRET',PI_OFFLINE:'1'});
 const connectOwner=async()=>{
  ownerErrors='';ownerOutput='';owner=spawn(process.execPath,['--import',fileURLToPath(new URL('./fixtures/pi-network-audit.mjs',import.meta.url)),join(resolve(process.env.AUGMENTOR_PI_TEST_ROOT||'.'),'dist/runtime/src/main.js')],{env,stdio:['ignore','pipe','pipe']});owner.stdout.on('data',data=>ownerOutput+=data);owner.stderr.on('data',data=>ownerErrors+=data);
  await until(()=>{if(owner.exitCode!==null)throw Error(ownerErrors);return ownerOutput.split('\n').some(line=>{try{return JSON.parse(line).ready;}catch{return false;}});},'owner ready');const socket=localConnect(join(state,'runtime.sock'));await once(socket,'connect');client=new PiConnection(socket,event=>events.push(event));await client.call('host.hello',{protocol:'augmentor-pi/1'});
 };await connectOwner();assert.equal((await client.call('observation.describe')).capturePayloads,false);
 const start=async(label,policy='read-only',surface='linux')=>{const sid='mcp-'+label,settings=await client.call('settings.describe');await client.call('settings.mutate',{ns:'permission',expectedRevision:settings.namespaces[0].revision,ops:[{op:'set',path:['defaultPreset'],value:policy}]});await client.call('session.create',{sessionId:sid,cwd,surface,selection:{provider:'fixture',model:'mcp-model'}});await client.call('events.subscribe',{sessionId:sid});await client.call('session.prompt',{sessionId:sid,requestId:'request-'+label,content:[{type:'text',text:'MCP_CASE='+label}]});return sid;};
 const settled=sid=>until(()=>events.some(frame=>frame.method==='session/event'&&frame.payload.sessionId===sid&&frame.payload.event.type==='turn/end'),'turn end '+sid).catch(async error=>{error.message+=' '+JSON.stringify({steps:[...steps],events:events.slice(-8).map(frame=>({method:frame.method,type:frame.payload?.event?.type,message:frame.payload?.message})),wire:(await calls()).slice(-12),ownerErrors});throw error;});
 for(const label of ['direct','deferred','script','http','blocked']){const sid=await start(label);await settled(sid);const history=await client.call('session.history',{sessionId:sid,maxMessages:100});assert(JSON.stringify(history).includes('Authored MCP case settled: '+label));const info=await client.call('session.mcpInfo',{sessionId:sid});assert(info.available);assert.equal(info.configurationErrors,0,JSON.stringify(info));assert.equal(info.projectConfiguration,false);assert(!JSON.stringify(info).includes('SYNTHETIC_MCP_SECRET'));assert(!JSON.stringify(info).includes(wire.address().port));if(label==='direct')assert((await calls()).some(row=>row.args?.query==='DIRECT_MARKER'),JSON.stringify({info,wire:await calls(),history}));if(label==='script')assert((await calls()).some(row=>row.args?.query==='SCRIPT_MARKER'),JSON.stringify({info,history,wire:(await calls()).slice(-15)}));}
 assert.equal((await calls()).filter(row=>row.method==='tools/call'&&row.args?.nonce==='blocked').length,0,'remote readOnlyHint cannot admit a mutation');assert((await calls()).some(row=>row.method==='tools/call'&&row.args?.query==='DIRECT_MARKER'));assert((await calls()).some(row=>row.method==='tools/call'&&row.args?.query==='DEFERRED_MARKER'));assert((await calls()).some(row=>row.method==='tools/call'&&row.args?.query==='SCRIPT_MARKER'));assert((await calls()).some(row=>row.method==='tools/call'&&row.args?.query==='HTTP_MARKER'));
 assert((await calls()).some(row=>row.method==='sampling-refused'&&row.errorCode===-32601),'server-requested model sampling is refused');assert(!received.some(body=>JSON.stringify(body.messages).includes('UNAUTHORIZED_SAMPLING')));assert(received.some(body=>JSON.stringify(body.messages).includes('AUTHORED_RESOURCE_ORIGINAL')));const deferredRequests=received.filter(body=>JSON.stringify(body.messages).includes('MCP_CASE=deferred'));assert(!deferredRequests[0].tools.some(tool=>tool.function.name==='mcp__deferred__search_record'));assert(deferredRequests[1].tools.some(tool=>tool.function.name==='mcp__deferred__search_record'));
 const directRequests=received.filter(body=>JSON.stringify(body.messages).includes('MCP_CASE=direct'));assert(!JSON.stringify(directRequests[1].messages).includes('DIRECT_FULL_ONLY'),'SDK-shortened model result omits its middle');assert(JSON.stringify(directRequests[3].messages).includes('DIRECT_FULL_ONLY'),'actual tool_result_excerpt recovers the full MCP result');const directOriginals=await client.call('observation.list',{sessionId:'mcp-direct',limit:500}),directOriginal=directOriginals.records.find(row=>row.kind==='tool/original'&&row.data.toolName==='mcp__direct__search_record');const directRaw=JSON.parse((await client.call('session.originalRead',{sessionId:'mcp-direct',entryId:directOriginal.data.entryId,limit:65536})).text).data;ownedOutputFiles.add(directRaw.result.details.fullOutputPath);if(process.platform!=='win32')assert.equal((await stat(directRaw.result.details.fullOutputPath)).mode&0o777,0o600);
 let sid=await start('approved','workspace-write');await until(()=>events.some(frame=>frame.method==='approval/requested'&&frame.payload.sessionId===sid),'nested approval');let approval=events.find(frame=>frame.method==='approval/requested'&&frame.payload.sessionId===sid);assert.equal(approval.payload.toolName,'mcp__script__write_record');assert.equal((await calls()).filter(row=>row.args?.nonce==='approved').length,0);await client.call('interaction.respond',{sessionId:sid,rpcId:approval.rpcId,value:{outcome:'allowed-once'}});await settled(sid);assert.equal((await calls()).filter(row=>row.args?.nonce==='approved').length,1);
 sid=await start('stopapproval','workspace-write');await until(()=>events.some(frame=>frame.method==='approval/requested'&&frame.payload.sessionId===sid),'approval to stop');await client.call('session.cancel',{sessionId:sid});await settled(sid);assert.equal((await calls()).filter(row=>row.args?.nonce==='stopapproval').length,0);
 sid=await start('unknown','danger-full-access');await settled(sid);assert.equal((await calls()).filter(row=>row.args?.nonce==='unknown').length,1,'lost mutation acknowledgment and recovery never replay it');const diagnostics=await client.call('observation.list',{sessionId:sid,limit:500});assert(diagnostics.records.some(row=>row.kind==='execution/state'&&row.data.actions?.some(action=>action.status==='unknown')));
 for(const label of failures.keys()){
  sid=await start(label,'danger-full-access');await settled(sid);assert.equal(httpMutations.get(label),1,label+' cannot authorize replay of a mutation');const failure=await client.call('observation.list',{sessionId:sid,limit:500});assert(failure.records.some(row=>row.kind==='execution/state'&&row.data.actions?.some(action=>action.status==='unknown')),label+' retains an unknown action outcome');
  assert(!JSON.stringify(received.filter(body=>JSON.stringify(body.messages).includes('MCP_CASE='+label))).includes('SYNTHETIC_PRIVATE_ERROR_BODY'));
  const linked=failure.records.filter(row=>row.kind==='integration/mcp-connection'&&row.data.event==='tool-send-started');assert.equal(linked.length,1);const link=linked[0],dispatch=failure.records.find(row=>row.kind==='tool/dispatch'&&row.data.toolCallId===link.data.agentCall.toolCallId);assert(dispatch);assert.equal(link.data.agentCall.sessionId,sid);assert.equal(link.data.agentCall.hostRequestId,'request-'+label);assert.equal(link.data.agentCall.hostTurnId,dispatch.turnId);assert.equal(link.data.agentCall.modelRequestObservationId,dispatch.requestId);assert(failure.records.some(row=>row.kind==='model/request'&&row.id===link.data.agentCall.modelRequestObservationId));assert.equal(link.data.agentCall.parentToolCallId,dispatch.data.parentToolCallId);assert.equal(link.data.agentCall.parentCoverage,'observed');
 }
 sid='mcp-expired';const previousEnds=events.filter(frame=>frame.method==='session/event'&&frame.payload.sessionId===sid&&frame.payload.event.type==='turn/end').length;
 const errorOriginals=await client.call('session.originalSearch',{sessionId:sid,query:'SYNTHETIC_PRIVATE_ERROR_BODY'});assert(errorOriginals.entries.length,'HTTP failure remains in native originals with capture disabled');const errorEntry=errorOriginals.entries[0],errorOriginal=JSON.parse((await client.call('session.originalRead',{sessionId:sid,entryId:errorEntry.entryId,entryHash:errorEntry.entryHash,limit:65536})).text);assert.equal(errorOriginal.customType,'augmentor-mcp-transport/1');assert.equal(errorOriginal.data.status,404);assert.equal(errorOriginal.data.body.text,'SYNTHETIC_PRIVATE_ERROR_BODY');assert.equal(errorOriginal.data.body.coverage,'complete');assert.equal(Buffer.from(errorOriginal.data.body.base64,'base64').toString(),'SYNTHETIC_PRIVATE_ERROR_BODY');assert(!JSON.stringify(errorOriginal).includes('SYNTHETIC_MCP_SECRET'));
 const beforeRebind=await client.call('observation.list',{sessionId:sid,limit:500}),failedSend=beforeRebind.records.find(row=>row.kind==='integration/mcp-connection'&&row.data.event==='tool-send-started');assert.deepEqual(errorOriginal.data.agentCall,failedSend.data.agentCall);const httpEvidence=await client.call('session.nativeHistory',{sessionId:sid});assert.equal(errorOriginal.data.agentCall.nativeSessionId,httpEvidence.nativeSessionId);assert.equal(errorOriginal.data.agentCall.toolCallId,'expired_1');assert(!Object.hasOwn(errorOriginal.data,'toolCallId'),'transport and canonical IDs retain separate named domains');
 await client.call('events.subscribe',{sessionId:sid});
 await client.call('session.prompt',{sessionId:sid,requestId:'after-failed-mutation',content:[{type:'text',text:'MCP_CASE=afterfailure'}]});await until(()=>events.filter(frame=>frame.method==='session/event'&&frame.payload.sessionId===sid&&frame.payload.event.type==='turn/end').length>previousEnds,'new explicit turn after failure');assert((await calls()).some(row=>row.args?.query==='AFTER_FAILED_MUTATION'),'the same SDK session can reconnect for a new explicit read');assert.equal(httpMutations.get('expired'),1);
 const recoveredRequests=received.filter(body=>JSON.stringify(body.messages).includes('MCP_CASE=afterfailure'));assert.equal(recoveredRequests.length,4);assert(!JSON.stringify(recoveredRequests.slice(0,3)).includes('SYNTHETIC_PRIVATE_ERROR_BODY'),'HTTP originals stay out of provider context until the explicit excerpt read');assert(JSON.stringify(recoveredRequests[3].messages).includes('SYNTHETIC_PRIVATE_ERROR_BODY'),'the actual excerpt tool recovers the retained HTTP failure text');assert(!JSON.stringify(recoveredRequests).includes('SYNTHETIC_MCP_SECRET'));assert.equal(httpMutations.get('expired'),1,'evidence recovery cannot replay the failed action');
 await writeFile(join(agent,'mcp.json'),JSON.stringify({mcpServers:{authweb:{url:'http://127.0.0.1:'+oauthWire.address().port+'/mcp',exposure:'codemode',timeout:1}},augmentor:{readOnlyTools:['mcp__authweb__search_record']}}));
 sid=await start('authsequential','danger-full-access');await settled(sid);const authRequests=received.filter(body=>JSON.stringify(body.messages).includes('MCP_CASE=authsequential'));assert.equal(oauthMutation,1,JSON.stringify(authRequests.at(-1).messages.filter(message=>message.role==='tool')));assert.equal(oauthRead,1);assert(JSON.stringify(authRequests.at(-1).messages).includes('AUTHORED_OAUTH_NEXT_RECEIPT'),'a separately requested read can reconnect after the SDK sign-in error');assert.match(JSON.stringify(authRequests.at(-1).messages.filter(message=>message.role==='tool')),/requires sign-in/i);assert(!JSON.stringify(authRequests).includes('SYNTHETIC_PRIVATE_AUTH_BODY'));const authEvidence=await client.call('observation.list',{sessionId:sid,limit:500});assert(authEvidence.records.some(row=>row.kind==='execution/state'&&row.data.actions?.some(action=>action.status==='unknown')));await writeFile(join(agent,'mcp.json'),configuration);
 const authInfo=await client.call('session.mcpInfo',{sessionId:sid});assert.equal(authInfo.servers.find(row=>row.name==='authweb').authorization.lastObserved.state,'sign-in-required');assert(!JSON.stringify(authInfo).includes('SYNTHETIC_PRIVATE_AUTH_BODY'));assert(authEvidence.records.some(row=>row.kind==='integration/mcp-authorization'&&row.data.state==='sign-in-required'&&row.data.retained===true));assert((await client.call('session.history',{sessionId:sid,maxMessages:100})).events.some(row=>row.event.type==='runtime/notice'&&row.event.data.message.includes('requires sign-in')));
 await writeFile(join(config,'resources.json'),JSON.stringify({sources:[],skills:[]}));sid=await start('unhooked','danger-full-access');await settled(sid);assert.equal((await calls()).filter(row=>row.args?.nonce==='unknown_unhooked').length,1,'nested outcomes do not depend on optional result/input hooks');const unhooked=await client.call('observation.list',{sessionId:sid,limit:500});assert(unhooked.records.some(row=>row.kind==='tool/original'&&row.data.coverage==='saved'));assert(unhooked.records.some(row=>row.kind==='execution/state'&&row.data.actions?.some(action=>action.status==='unknown')));await writeFile(join(config,'resources.json'),JSON.stringify({sources:[hooks],skills:[]}));
 sid=await start('cancel','danger-full-access');await until(async()=> (await calls()).some(row=>row.name==='wait_record'),'remote wait dispatched');await client.call('session.cancel',{sessionId:sid});await settled(sid);await until(async()=> (await calls()).some(row=>row.method==='cancelled'),'remote cancellation delivered');
 sid=await start('nestedcancel','danger-full-access');await until(async()=> (await calls()).some(row=>row.name==='wait_record'&&row.server==='script'),'nested remote wait dispatched');await client.call('session.cancel',{sessionId:sid});await settled(sid);await until(async()=> (await calls()).some(row=>row.method==='cancelled'&&row.server==='script'),'nested remote cancellation delivered');assert.equal((await calls()).filter(row=>row.args?.nonce==='AFTER_NESTED_STOP').length,0);
 const startsBefore=(await calls()).filter(row=>row.method==='start').length;sid=await start('browser','read-only','browser');await settled(sid);assert.equal((await client.call('session.mcpInfo',{sessionId:sid})).available,false);assert.equal((await calls()).filter(row=>row.method==='start').length,startsBefore);assert.equal((await calls()).filter(row=>row.args?.query==='BROWSER_MUST_NOT_RUN').length,0);
 const observations=await client.call('observation.list',{sessionId:'mcp-script',limit:500});assert(observations.records.some(row=>row.kind==='tool/start'&&row.data.name==='mcp__script__search_record'),'nested calls are observed');assert(observations.records.some(row=>row.kind==='tool/end'&&row.data.name==='mcp__script__search_record'));
 const nested=observations.records.find(row=>row.kind==='tool/original'&&row.data.toolName==='mcp__script__search_record');assert.equal(nested.data.coverage,'saved');assert.equal(nested.data.parentToolCallId,'script_1');
 const search=await client.call('session.originalSearch',{sessionId:'mcp-script',query:'TOOL_RAW_BODY_ONLY'});assert(search.entries.some(row=>row.entryId===nested.data.entryId));const original=search.entries.find(row=>row.entryId===nested.data.entryId),originalParams={sessionId:'mcp-script',source:'pi',entryId:original.entryId,entryHash:original.entryHash,pathHash:original.pathHash,sessionIdentity:search.sessionIdentity,limit:65536};const originalRead=await client.call('session.originalRead',originalParams),saved=JSON.parse(originalRead.text);assert.equal(saved.customType,'augmentor-tool-original/1');assert.equal(saved.data.input.query,'SCRIPT_MARKER');assert.equal(saved.data.result.content[1].type,'image');assert.equal(saved.data.result.structuredContent.structuredContent.source,'fixture://record');assert(!received.some(body=>JSON.stringify(body.messages).includes('TOOL_RAW_BODY_ONLY')),'native evidence is not silently injected into model context');
 const unknownOriginal=diagnostics.records.find(row=>row.kind==='tool/original'&&row.data.toolName==='mcp__script__write_record'&&row.data.coverage==='saved');const rawFailure=await client.call('session.originalRead',{sessionId:'mcp-unknown',entryId:unknownOriginal.data.entryId,limit:65536});const failure=JSON.parse(rawFailure.text).data;assert.equal(failure.result.isError,true,'original precedes misleading result hooks');assert(!JSON.stringify(failure.result).includes('MISLEADING_TRANSFORMED_RESULT'));assert.equal(failure.input.nonce,'unknown');
 assert.equal(await readFile(join(agent,'mcp.json'),'utf8'),configuration);assert.equal(existsSync(join(home,'.pi','agent')),false,'SDK defaults cannot touch another Pi profile');assert.equal(existsSync(join(state,'mcp-logs')),false,'server logs remain opt-in');assert((await calls()).filter(row=>row.method==='start').every(row=>row.agentDir===agent));assert.equal(ownerErrors,'');assert((await readFile(network,'utf8')).trim().split('\n').every(line=>JSON.parse(line).allowed));
 await client.call('observation.clear',{sessionId:'mcp-script'});assert.equal((await client.call('session.originalRead',originalParams)).text,originalRead.text);
 const ended=once(owner,'exit');owner.kill('SIGTERM');await ended;assert.equal(owner.exitCode,0);for(const row of (await calls()).filter(row=>row.method==='start'))assert.equal(alive(row.pid),false,'MCP child exits with its actual owner');client.close();
 const beforeRestartCalls=await calls(),beforeRestartRequests=received.length;await connectOwner();assert.equal((await client.call('session.mcpInfo',{sessionId:'mcp-script'})).available,false,'cold catalog reads cannot load or connect servers');assert.equal((await client.call('session.originalRead',originalParams)).text,originalRead.text);assert.deepEqual(await calls(),beforeRestartCalls);assert.equal(received.length,beforeRestartRequests,'cold original inspection performs no inference');
 for(const [label,value] of [['empty',JSON.stringify({mcpServers:{}})],['invalid','{"mcpServers":"SYNTHETIC_PRIVATE_CONFIG_SECRET"}'],['unavailable',JSON.stringify({mcpServers:{offline:{command:process.execPath,args:['-e','process.exit(2)'],exposure:'direct',timeout:1}}})]]){
  await writeFile(join(agent,'mcp.json'),value);sid=await start(label);await settled(sid);const info=await client.call('session.mcpInfo',{sessionId:sid});assert.equal(info.configurationErrors,label==='invalid'?1:0);assert(!JSON.stringify(info).includes('SYNTHETIC_PRIVATE_CONFIG_SECRET'));assert((await client.call('session.history',{sessionId:sid,maxMessages:100})).events.some(row=>JSON.stringify(row).includes('Authored MCP case settled: '+label)),'configuration failure leaves ordinary chat available');const request=received.find(body=>JSON.stringify(body.messages).includes('MCP_CASE='+label));assert(!request.tools.some(tool=>['codemode','tool_search','mcp__offline__search_record'].includes(tool.function.name)));
 }
 const catalogName='catalog_'+'x'.repeat(70);await writeFile(join(agent,'mcp.json'),JSON.stringify({mcpServers:{[catalogName]:{command:process.execPath,args:[fixture,'--stdio','catalog',log],exposure:'deferred',timeout:1}}}));sid=await start('catalog');await settled(sid);const catalog=await client.call('session.mcpInfo',{sessionId:sid});assert.equal(catalog.serverCount,1);assert.equal(catalog.servers[0].toolCount,600);assert.equal(catalog.servers[0].toolNames.length,256);assert.equal(catalog.servers[0].omittedToolNames,344);assert.equal(catalog.servers[0].declaredToolNames.length,0);assert(JSON.stringify(catalog).length<32768,'bounded metadata remains usable with a large actual SDK catalog');
 await writeFile(join(agent,'mcp.json'),JSON.stringify({mcpServers:{logs:{command:process.execPath,args:[fixture,'--stdio','logs',log],timeout:1}},augmentor:{retainServerLogs:true}}));sid=await start('logs');await settled(sid);const logPath=join(state,'mcp-logs',sid+'.log');await until(()=>existsSync(logPath),'opt-in server log');assert((await readFile(logPath,'utf8')).includes('SYNTHETIC_SERVER_LOG'));if(process.platform!=='win32'){assert.equal((await stat(logPath)).mode&0o777,0o600);assert.equal((await stat(join(state,'mcp-logs'))).mode&0o777,0o700);}
 await writeFile(join(agent,'mcp.json'),configuration);const finalExit=once(owner,'exit');owner.kill('SIGTERM');await finalExit;assert.equal(owner.exitCode,0);for(const row of (await calls()).filter(row=>row.method==='start'))assert.equal(alive(row.pid),false,'all configured children exit after restart and configuration changes');assert.equal(existsSync(join(home,'.pi','agent')),false);
});
