// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
// Actual private owner, public SDK and independently authored provider/OAuth wire.
import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {managementOwner,until} from './fixtures/mcp-management-owner.mjs';
test('reused model call IDs retain distinct exact native/MCP operation links through reload, clearing, branch and cold restart',{timeout:60000},async t=>{
 const owner=await managementOwner(t);await owner.stop();const requests=[];
 const provider=http.createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;requests.push(JSON.parse(raw));const first=requests.length%2===1,delta=first?{role:'assistant',tool_calls:[{index:0,id:'authored-reused-call',type:'function',function:{name:'mcp__web__read_record',arguments:'{}'}}]}:{role:'assistant',content:'Authored repeated calls settled.'};res.writeHead(200,{'content-type':'text/event-stream'}).end('data: '+JSON.stringify({id:'authored-causal',choices:[{index:0,delta,finish_reason:first?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n');});provider.listen(0,'127.0.0.1');await once(provider,'listening');t.after(async()=>{provider.closeAllConnections();await new Promise(done=>provider.close(done));});
 const models=JSON.parse(await readFile(join(owner.agent,'models.json'),'utf8'));models.providers.fixture.baseUrl='http://127.0.0.1:'+provider.address().port+'/v1';await writeFile(join(owner.agent,'models.json'),JSON.stringify(models));await owner.start();const sid=await owner.create();
 await owner.client.call('session.mcpAction',{sessionId:sid,requestId:'authorize',server:'web',action:'login'});await owner.authorize(sid,'authorize');const captured=[];
 for(const n of [1,2]){
  if(n===2){const profile=await owner.client.call('session.mcpProfile',{sessionId:sid}),document=JSON.parse(profile.text);document.augmentor.retainServerLogs=true;await owner.client.call('session.mcpConfigure',{sessionId:sid,requestId:'reload-options',operation:'save-profile',expectedRevision:profile.revision,text:JSON.stringify(document)});assert.equal((await owner.settle(sid,'reload-options')).result,'session-options-applied');}
  const ends=owner.events.filter(row=>row.method==='session/event'&&row.payload.event.type==='turn/end').length;await owner.client.call('session.prompt',{sessionId:sid,requestId:'authored-input-'+n,content:[{type:'text',text:'Read the authored record once.'}]});await until(()=>requests.length===n*2&&owner.events.filter(row=>row.method==='session/event'&&row.payload.event.type==='turn/end').length===ends+1,'explicit repeated-ID turn');
  const observations=(await owner.client.call('observation.list',{sessionId:sid,limit:500})).records,original=observations.find(row=>row.kind==='tool/original'&&row.data.agentCall?.hostRequestId==='authored-input-'+n);assert(original,'real pre-hook original carries its owned execution identity');const identity=original.data.agentCall;assert.equal(identity.toolCallId,'authored-reused-call');assert.equal(identity.parentCoverage,'observed');assert.equal(identity.parentToolCallId,undefined);
  const sent=observations.find(row=>row.kind==='integration/mcp-connection'&&row.data.event==='tool-send-started'&&row.data.agentCall?.operationId===identity.operationId),reply=observations.find(row=>row.kind==='integration/mcp-connection'&&row.data.event==='tool-response'&&row.data.agentCall?.operationId===identity.operationId);assert(sent&&reply);assert.equal(sent.data.requestId,reply.data.requestId);assert.deepEqual(sent.data.agentCall,identity);assert(observations.some(row=>row.kind==='model/request'&&row.id===identity.modelRequestObservationId));assert.equal(identity.hostTurnId,original.turnId);
  const native=await owner.client.call('session.originalRead',{sessionId:sid,entryId:original.data.entryId,limit:65536}),data=JSON.parse(native.text);assert.deepEqual(data.data.agentCall,identity);assert.equal(data.data.toolCallId,'authored-reused-call');captured.push({identity,entryId:data.id,text:native.text});
 }
 assert.notEqual(captured[0].identity.operationId,captured[1].identity.operationId);assert.notEqual(captured[0].identity.hostTurnId,captured[1].identity.hostTurnId);assert.notEqual(captured[0].identity.modelRequestObservationId,captured[1].identity.modelRequestObservationId);assert.equal(captured[0].identity.nativeSessionId,captured[1].identity.nativeSessionId);assert.equal(owner.wire.stats.tools,2);
 const file=join(owner.state,'sessions',sid,(await readdir(join(owner.state,'sessions',sid))).find(name=>name.endsWith('.jsonl'))),before=await readFile(file);const history=await owner.client.call('session.history',{sessionId:sid,maxMessages:100}),target=history.events.find(row=>row.event.type==='assistant/message'&&row.event.data.message.content.some(part=>part.type==='text'&&part.text.includes('Authored repeated calls settled.')));
 assert(target);const child='authored-earlier-branch';await owner.client.call('session.branch',{sessionId:sid,newSessionId:child,messageSeq:target.event.seq,mode:'reply'});assert.equal(requests.length,4);assert.deepEqual(await readFile(file),before);
 const inherited=await owner.client.call('session.originalRead',{sessionId:child,entryId:captured[0].entryId,limit:65536});assert.equal(inherited.text,captured[0].text,'inherited originals keep their originating session/operation identity');await assert.rejects(owner.client.call('session.originalRead',{sessionId:child,entryId:captured[1].entryId,limit:65536}),/Saved native entry is not in this conversation/);
 await owner.client.call('observation.clear',{sessionId:sid});assert.deepEqual(await readFile(file),before);for(const row of captured)assert.equal((await owner.client.call('session.originalRead',{sessionId:sid,entryId:row.entryId,limit:65536})).text,row.text);
 const stats=structuredClone(owner.wire.stats);await owner.stop();await owner.start();for(const row of captured)assert.equal((await owner.client.call('session.originalRead',{sessionId:sid,entryId:row.entryId,limit:65536})).text,row.text);assert.equal((await owner.client.call('session.mcpInfo',{sessionId:sid})).available,false);assert.equal(requests.length,4);assert.deepEqual(owner.wire.stats,stats);assert.deepEqual((await readFile(file)).subarray(0,before.length),before);assert.deepEqual(owner.wire.errors,[]);
});
