// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
// Actual owner/public SDK. Fault injection replaces only a public loader method in this isolated child.
import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {readFile,writeFile,readdir,unlink,mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {managementOwner,until} from './fixtures/mcp-management-owner.mjs';
const rows=async file=>(await readFile(file,'utf8')).trim().split('\n').filter(Boolean).map(line=>JSON.parse(line));
test('a pre-runner public loader failure remains partial and explicit repair preserves the same owner, namespace policy and history',{timeout:90000},async t=>{
 const owner=await managementOwner(t);await owner.stop();
 const fail=join(owner.root,'fail-loader'),log=join(owner.root,'loader-boundary.jsonl'),extension=join(owner.root,'authored-loader-owner.mjs'),preload=join(owner.root,'authored-loader-fault.mjs');
 const sdk=join(resolve(process.env.AUGMENTOR_PI_TEST_ROOT||'.'),'node_modules/@earendil-works/pi-coding-agent'),metadata=JSON.parse(await readFile(join(sdk,'package.json'),'utf8')),entry=metadata.exports['.'],sdkUrl=pathToFileURL(join(sdk,typeof entry==='string'?entry:entry.import)).href;
 await writeFile(preload,'import {existsSync,appendFileSync} from "node:fs";import {DefaultResourceLoader} from '+JSON.stringify(sdkUrl)+';const original=DefaultResourceLoader.prototype.reload;DefaultResourceLoader.prototype.reload=async function(...args){if(existsSync('+JSON.stringify(fail)+')&&this.getExtensions().extensions.some(row=>row.commands.has("authored-loader-owner"))){appendFileSync('+JSON.stringify(log)+',JSON.stringify({kind:"pre-runner-loader-rejection"})+"\\n");throw Error("AUTHORED_PRIVATE_LOADER_FAILURE");}return original.apply(this,args);};');
 await writeFile(extension,'import {appendFileSync} from "node:fs";export default pi=>{pi.registerCommand("authored-loader-owner",{description:"Authored marker only",handler:async()=>{}});pi.registerMcpServer("foreign-owned",'+JSON.stringify({...owner.wire.config,enabled:false})+');pi.on("session_start",(event,ctx)=>{appendFileSync('+JSON.stringify(log)+',JSON.stringify({kind:"start",reason:event.reason,nativeSessionId:ctx.sessionManager.getSessionId()})+"\\n");});pi.on("session_shutdown",event=>{appendFileSync('+JSON.stringify(log)+',JSON.stringify({kind:"shutdown",reason:event.reason})+"\\n");});};');
 await writeFile(join(owner.config,'resources.json'),JSON.stringify({sources:[extension],skills:[]}));owner.env.NODE_OPTIONS='--import='+pathToFileURL(preload).href;
 const requests=[];const provider=http.createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;requests.push(JSON.parse(raw));const first=requests.length%2===1,delta=first?{role:'assistant',tool_calls:[{index:0,id:'authored-loader-call-'+requests.length,type:'function',function:{name:'mcp__web__read_record',arguments:'{}'}}]}:{role:'assistant',content:'Authored loader recovery read settled.'};res.writeHead(200,{'content-type':'text/event-stream'}).end('data: '+JSON.stringify({id:'authored-loader',choices:[{index:0,delta,finish_reason:first?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n');});provider.listen(0,'127.0.0.1');await once(provider,'listening');t.after(async()=>{provider.closeAllConnections();await new Promise(done=>provider.close(done));});
 const models=JSON.parse(await readFile(join(owner.agent,'models.json'),'utf8'));models.providers.fixture.baseUrl='http://127.0.0.1:'+provider.address().port+'/v1';await writeFile(join(owner.agent,'models.json'),JSON.stringify(models));await owner.start();const sid=await owner.create(),other=await owner.create('other-loader-owner'),pid=owner.owner.pid;
 await owner.client.call('events.subscribe',{sessionId:sid});await owner.client.call('session.mcpAction',{sessionId:sid,requestId:'authorize-loader',server:'web',action:'login'});await owner.authorize(sid,'authorize-loader');
 const run=async id=>{const count=requests.length,ends=owner.events.filter(row=>row.method==='session/event'&&row.payload.event.type==='turn/end').length;await owner.client.call('session.prompt',{sessionId:sid,requestId:id,content:[{type:'text',text:'Read the authored record once.'}]});await until(()=>requests.length===count+2&&owner.events.filter(row=>row.method==='session/event'&&row.payload.event.type==='turn/end').length===ends+1,'actual explicit read');};
 await run('before-loader-fault');const file=join(owner.state,'sessions',sid,(await readdir(join(owner.state,'sessions',sid))).find(name=>name.endsWith('.jsonl'))),before=await readFile(file),selection=await owner.client.call('session.models',{sessionId:sid}),nativeId=(await rows(file))[0].id;
 await owner.client.call('session.cancel',{sessionId:sid});await owner.client.call('session.prompt',{sessionId:sid,requestId:'keep-paused',mode:'queue',resumeQueue:false,content:[{type:'text',text:'Keep this prompt paused.'}]});const queue=await owner.client.call('session.queue',{sessionId:sid});
 const profile=await owner.client.call('session.mcpProfile',{sessionId:sid}),document=JSON.parse(profile.text);document.augmentor.retainServerLogs=true;const input={sessionId:sid,requestId:'catastrophic-loader',operation:'save-profile',expectedRevision:profile.revision,text:JSON.stringify(document)};
 await writeFile(fail,'fault');const stats=structuredClone(owner.wire.stats);await owner.client.call('session.mcpConfigure',input);const failed=await owner.settle(sid,input.requestId);assert.equal(failed.result,'profile-saved-partial');assert.equal(failed.appliedSessions,0);assert.equal((await rows(log)).filter(row=>row.kind==='pre-runner-loader-rejection').length,1);assert.equal((await rows(log)).filter(row=>row.kind==='start').length,2,'the failed loader never constructs/starts a replacement runtime');
 const broken=await owner.client.call('session.mcpInfo',{sessionId:sid});assert.equal(broken.available,false);assert(broken.configuration.pendingSessionOptions);assert.equal(owner.owner.pid,pid);assert.equal(requests.length,2);assert.equal(owner.wire.stats.tools,stats.tools);assert.deepEqual((await readFile(file)).subarray(0,before.length),before);assert.deepEqual(await owner.client.call('session.queue',{sessionId:sid}),queue);assert(!JSON.stringify(owner.events).includes('AUTHORED_PRIVATE_LOADER_FAILURE'));
 for(const mode of [undefined,'queue'])await assert.rejects(owner.client.call('session.prompt',{sessionId:sid,requestId:'refused-loader-'+(mode??'direct'),mode,content:[{type:'text',text:'Do not admit this prompt.'}]}),/configuration has not settled/);await assert.rejects(owner.client.call('session.continueQueue',{sessionId:sid}),/configuration has not settled/);assert.deepEqual(await owner.client.call('session.queue',{sessionId:sid}),queue);assert.equal(requests.length,2);
 await unlink(fail);const saved=await owner.client.call('session.mcpProfile',{sessionId:sid}),conflict=JSON.parse(saved.text);conflict.mcpServers.foreign_owned={...owner.wire.config,enabled:false};await owner.client.call('session.mcpConfigure',{sessionId:sid,requestId:'reject-stale-foreign',operation:'save-profile',expectedRevision:saved.revision,text:JSON.stringify(conflict)});assert.equal((await owner.settle(sid,'reject-stale-foreign')).result,'configuration-not-saved');assert.deepEqual(await owner.client.call('session.mcpProfile',{sessionId:sid}),saved);
 await owner.client.call('session.mcpConfigure',{...input,requestId:'explicit-loader-repair',expectedRevision:saved.revision});const repaired=await owner.settle(sid,'explicit-loader-repair');assert.equal(repaired.result,'session-options-applied','An explicit repair must escape the invalidated pre-reload API');assert.equal(repaired.reloadedSessions,2);assert.equal(repaired.pendingSessionOptions,false);assert.equal(owner.owner.pid,pid);
 for(const sessionId of [sid,other]){const catalog=await owner.client.call('session.mcpInfo',{sessionId});assert(catalog.available&&catalog.retainServerLogs);assert.equal(catalog.configuration.registrationPending,false);}assert.deepEqual(await owner.client.call('session.queue',{sessionId:sid}),queue);assert.deepEqual(await owner.client.call('session.models',{sessionId:sid}),selection);assert.deepEqual((await readFile(file)).subarray(0,before.length),before);assert.equal((await rows(file))[0].id,nativeId);assert.equal(requests.length,2);assert.equal(owner.wire.stats.tools,stats.tools);
 await owner.client.call('session.updateQueue',{sessionId:sid,itemId:'keep-paused',action:{kind:'remove'}});await run('after-loader-repair');assert.equal(owner.wire.stats.tools,stats.tools+1);const observed=(await owner.client.call('observation.list',{sessionId:sid,limit:500})).records;assert.equal(observed.filter(row=>row.kind==='model/request').length,4);assert.equal(observed.filter(row=>row.kind==='execution/reasoning').length,4);const originals=(await rows(file)).filter(row=>row.customType==='augmentor-tool-original/1');assert.equal(originals.length,2);assert(originals.every(row=>row.data.agentCall.nativeSessionId===nativeId));assert.deepEqual(owner.wire.errors,[]);
});

test('public registration preflight bounds external namespace recovery and never treats an unloaded owner as a snapshot',{timeout:15000},async t=>{
 const root=await mkdtemp(join(tmpdir(),'augmentor-mcp-namespace-bound-')),agent=join(root,'agent');await mkdir(agent,{mode:0o700});t.after(()=>rm(root,{recursive:true,force:true}));
 const tree=resolve(process.env.AUGMENTOR_PI_TEST_ROOT||'.'),sdk=join(tree,'node_modules/@earendil-works/pi-coding-agent'),metadata=JSON.parse(await readFile(join(sdk,'package.json'),'utf8')),entry=metadata.exports['.'];const {DefaultResourceLoader,SettingsManager}=await import(pathToFileURL(join(sdk,typeof entry==='string'?entry:entry.import)));const {ManagedMcp}=await import(pathToFileURL(join(tree,'dist/runtime/src/mcp.js')));
 const mcp=new ManagedMcp(agent,root,'authored-bounded'),profile={servers:new Map(),document:{mcpServers:{}},readTools:new Set(),autoEnableCodemode:true,retainLogs:false};assert.throws(()=>mcp.preflight(profile),/usable Native conversation/);
 const loader=new DefaultResourceLoader({cwd:root,agentDir:agent,settingsManager:SettingsManager.inMemory({packages:[],enableInstallTelemetry:false,enableAnalytics:false,cacheWarming:'off',defaultProjectTrust:'never'}),noExtensions:true,noSkills:true,noContextFiles:true,noThemes:true,noPromptTemplates:true,extensionFactories:[...mcp.factories(),pi=>{for(let n=0;n<257;n++)pi.registerMcpServer('foreign-'+n,{url:'http://127.0.0.1:9',enabled:false});}]});await loader.reload();assert.deepEqual(loader.getExtensions().errors,[]);assert.throws(()=>mcp.preflight(profile),/Too many extension-owned MCP namespaces/);
});

test('a late approved-resource namespace conflict cannot report a successfully applied managed reload',{timeout:60000},async t=>{
 const owner=await managementOwner(t);await owner.stop();const extension=join(owner.root,'authored-late-namespace.mjs'),flag=join(owner.root,'late-namespace'),config={...owner.wire.config,enabled:false};
 await writeFile(extension,'import {existsSync} from "node:fs";export default pi=>{pi.registerMcpServer("foreign-owned",'+JSON.stringify(config)+');if(existsSync('+JSON.stringify(flag)+'))pi.registerMcpServer("web",'+JSON.stringify(config)+');};');await writeFile(join(owner.config,'resources.json'),JSON.stringify({sources:[extension],skills:[]}));await owner.start();const sid=await owner.create(),pid=owner.owner.pid;
 await owner.client.call('session.cancel',{sessionId:sid});const queue=await owner.client.call('session.queue',{sessionId:sid}),before=await owner.client.call('session.mcpProfile',{sessionId:sid}),document=JSON.parse(before.text);document.augmentor.retainServerLogs=true;
 await writeFile(flag,'register the new authored external namespace');
 await owner.client.call('session.mcpConfigure',{sessionId:sid,requestId:'late-namespace',operation:'save-profile',expectedRevision:before.revision,text:JSON.stringify(document)});const row=await owner.settle(sid,'late-namespace'),info=await owner.client.call('session.mcpInfo',{sessionId:sid});assert(info.configurationErrors>0,'The refreshed factory must actually reject the managed registration');assert.equal(info.servers.find(server=>server.name==='web').enabled,false,'The observed external registration owns the disabled namespace');assert.equal(row.result,'profile-saved-partial','A caught managed registration error must not become an applied receipt');
 assert(info.configuration.pendingSessionOptions&&info.configuration.registrationPending);assert.equal(owner.owner.pid,pid);assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);await assert.rejects(owner.client.call('session.prompt',{sessionId:sid,requestId:'do-not-admit-conflict',mode:'queue',content:[{type:'text',text:'Do not run.'}]}),/configuration has not settled/);assert.deepEqual(await owner.client.call('session.queue',{sessionId:sid}),queue);
 const saved=await owner.client.call('session.mcpProfile',{sessionId:sid}),repaired=JSON.parse(saved.text);delete repaired.mcpServers.web;await owner.client.call('session.mcpConfigure',{sessionId:sid,requestId:'remove-conflicting-managed-name',operation:'save-profile',expectedRevision:saved.revision,text:JSON.stringify(repaired)});assert.equal((await owner.settle(sid,'remove-conflicting-managed-name')).result,'session-options-applied');assert.equal((await owner.client.call('session.mcpInfo',{sessionId:sid})).configuration.registrationPending,false);assert.equal(owner.owner.pid,pid);assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);assert.deepEqual(await owner.client.call('session.queue',{sessionId:sid}),queue);assert.deepEqual(owner.wire.errors,[]);
});
