// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,stat} from 'node:fs/promises';
import {join} from 'node:path';
import {managementOwner,until} from './fixtures/mcp-management-owner.mjs';

test('actual Pi owner persists MCP controls, applies all loaded Native registrations and keeps private profile values out of inspection',{timeout:90000},async t=>{
 const owner=await managementOwner(t),sid=await owner.create(),other=await owner.create('other');await owner.client.call('events.subscribe',{sessionId:sid});
 const call=(method,params={})=>owner.client.call(method,{sessionId:sid,...params}),file=join(owner.agent,'mcp.json');
 const edit=async(requestId,params)=>{const before=await call('session.mcpProfile');const input={requestId,expectedRevision:before.revision,...params};await call('session.mcpConfigure',input);const row=await owner.settle(sid,requestId);assert.equal(row.result,requestId==='full'?'session-options-applied':'registration-events-settled',JSON.stringify(row));assert.equal(row.appliedSessions,2);assert.equal(row.expectedSessions,2);return input;};
 await call('session.mcpAction',{requestId:'login',server:'web',action:'login'});await owner.authorize(sid,'login');
 await edit('disable',{operation:'set-enabled',server:'web',enabled:false});
 for(const sessionId of [sid,other]){const info=await owner.client.call('session.mcpInfo',{sessionId});assert.equal(info.servers.find(row=>row.name==='web').enabled,false);assert(!info.configuration.registrationPending);}
 assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);
 await edit('enable',{operation:'set-enabled',server:'web',enabled:true});
 await edit('hidden',{operation:'set-exposure',server:'web',exposure:'hidden'});
 let info=await call('session.mcpInfo');assert.equal(info.servers.find(row=>row.name==='web').exposure,'hidden');assert.deepEqual(info.servers.find(row=>row.name==='web').declaredToolNames,[]);
 await edit('direct',{operation:'set-exposure',server:'web',exposure:'direct'});info=await call('session.mcpInfo');assert(info.servers.find(row=>row.name==='web').declaredToolNames.includes('mcp__web__read_record'));
 const before=await call('session.mcpProfile'),document=JSON.parse(before.text);document.authoredUnrelated={keep:['one','two']};document.augmentor.retainServerLogs=true;document.autoEnableCodemode=false;document.mcpServers.header.headers.Authorization='Bearer AUTHORED_CONFIG_PRIVATE_SECRET';delete document.mcpServers.disabled;
 const saved=await edit('full',{operation:'save-profile',text:JSON.stringify(document)});info=await call('session.mcpInfo');assert.equal(info.servers.length,2);assert.equal(info.retainServerLogs,true);assert.equal(info.configuration.pendingSessionOptions,false);const receipt=await call('session.mcpActionStatus',{requestId:'full'});assert.equal(receipt.pendingSessionOptions,false);assert.equal(receipt.reloadedSessions,2);
 for(const sessionId of [sid,other]){const loaded=await owner.client.call('session.mcpInfo',{sessionId});assert.equal(loaded.retainServerLogs,true);assert.equal(loaded.configuration.pendingSessionOptions,false);assert(!loaded.activeDiscoveryTools.includes('codemode'),'automatic activation is removed in already loaded owners');}
 await edit('preserve',{operation:'set-enabled',server:'header',enabled:false});const actual=JSON.parse(await readFile(file,'utf8'));assert.deepEqual(actual.authoredUnrelated,{keep:['one','two']});assert.equal(actual.mcpServers.header.headers.Authorization,'Bearer AUTHORED_CONFIG_PRIVATE_SECRET');if(process.platform!=='win32')assert.equal((await stat(file)).mode&0o777,0o600);
 const snapshot=structuredClone(owner.wire.stats);assert((await call('session.mcpConfigure',saved)).duplicate);assert.deepEqual(owner.wire.stats,snapshot);await assert.rejects(call('session.mcpConfigure',{...saved,text:JSON.stringify({...document,authoredUnrelated:'different'})}),/different parameters/);
 await assert.rejects(call('session.mcpConfigure',{requestId:'stale',operation:'save-profile',expectedRevision:before.revision,text:before.text}),/changed/);
 const inspection=await call('inspection.open'),inspected=new URL(inspection.url),token=new URLSearchParams(inspected.hash.slice(1)).get('token');for(const method of ['session.mcpProfile','session.mcpConfigure']){const response=await fetch(inspected.origin+'/api/rpc',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',Origin:inspected.origin},body:JSON.stringify({id:'inspection',method,params:{sessionId:sid}})});assert.equal(response.status,400);assert((await response.json()).error.message.includes('read-only'));}
 for(const evidence of [JSON.stringify(await call('session.mcpInfo')),JSON.stringify(owner.events),JSON.stringify(await owner.client.call('observation.list',{sessionId:sid,limit:500})),await readFile(join(owner.state,'mcp-management.json'),'utf8')])assert(!evidence.includes('AUTHORED_CONFIG_PRIVATE_SECRET'));
 assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);await owner.stop();await owner.start();assert((await call('session.mcpConfigure',saved)).duplicate);assert.equal((await call('session.mcpInfo')).available,false);
 await call('session.selectModel',owner.selection);await call('events.subscribe');info=await call('session.mcpInfo');assert.equal(info.retainServerLogs,true);assert.equal(info.configuration.pendingSessionOptions,false);assert.equal(info.servers.find(row=>row.name==='web').exposure,'direct');
 // A separate explicitly authorized turn checks the preserved single SDK loop.
 await call('session.prompt',{requestId:'explicit-read',content:[{type:'text',text:'Read the authored record once.'}]});await until(()=>owner.events.some(frame=>frame.method==='session/event'&&frame.payload.event.type==='turn/end'),'explicit read');assert.equal(owner.wire.stats.tools,1);assert.equal(owner.requests.length,2);assert.deepEqual(owner.wire.errors,[]);
});

test('public profile validation starts no server and rejects invalid definitions without saving or leaking values',{timeout:60000},async t=>{
 const owner=await managementOwner(t),sid=await owner.create(),call=(method,params={})=>owner.client.call(method,{sessionId:sid,...params}),before=await call('session.mcpProfile');
 const configs=[{mcpServers:{bad:{url:'http://AUTHORED_PRIVATE.invalid',exposure:'invalid'}}},{mcpServers:{'same-name':owner.wire.config,same_name:owner.wire.config}},{mcpServers:{bad:{command:'AUTHORED_MUST_NOT_EXECUTE',timeout:-1}}}];
 for(const server of ['__proto__','constructor','toString'])await assert.rejects(call('session.mcpConfigure',{requestId:'foreign-'+server,operation:'set-enabled',server,enabled:false,expectedRevision:before.revision}),/Choose a server/);
 assert.equal((await call('session.mcpInfo')).servers.find(row=>row.name==='web').enabled,true);assert.deepEqual(await call('session.mcpProfile'),before);
 for(const [index,document] of configs.entries()){const requestId='invalid-'+index,stats=structuredClone(owner.wire.stats);await call('session.mcpConfigure',{requestId,operation:'save-profile',expectedRevision:before.revision,text:JSON.stringify(document)});const row=await owner.settle(sid,requestId);assert.equal(row.state,'failed');assert.equal(row.result,'configuration-not-saved');assert.deepEqual(await call('session.mcpProfile'),before);assert.deepEqual(owner.wire.stats,stats);assert(!JSON.stringify(row).includes('AUTHORED_PRIVATE'));}
 assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);
 // An external revision arriving during asynchronous preparation must win.
 const input={requestId:'external',operation:'save-profile',expectedRevision:before.revision,text:JSON.stringify({mcpServers:{}})};
 await writeFile(join(owner.agent,'mcp.json'),JSON.stringify({mcpServers:{},authoredExternal:true}));await assert.rejects(call('session.mcpConfigure',input),/changed/);assert.equal(JSON.parse(await readFile(join(owner.agent,'mcp.json'),'utf8')).authoredExternal,true);
});

test('configuration Cancel waits for real SDK connection settlement; interrupted saved changes stay unknown without replay',{timeout:60000},async t=>{
 const owner=await managementOwner(t),sid=await owner.create(),call=(method,params={})=>owner.client.call(method,{sessionId:sid,...params});
 t.after(()=>owner.wire.releaseInitialize());
 const configure=async requestId=>{const profile=await call('session.mcpProfile');return {requestId,operation:'set-enabled',server:'header',enabled:true,expectedRevision:profile.revision};};
 owner.wire.holdInitialize();let input=await configure('held');await call('session.mcpConfigure',input);await until(async()=>owner.wire.pendingInitialize>0&&!!(await call('session.mcpActionStatus',{requestId:'held'})).savedRevision,'held initialization and saved profile before SDK settlement');
 let row=await call('session.mcpCancelAction',{requestId:'held'});assert.equal(row.state,'cancel-requested');assert(row.savedRevision);assert.equal((await call('session.mcpInfo')).management.busy,true);try{await assert.rejects(call('session.prompt',{requestId:'must-wait',content:[{type:'text',text:'Do not dispatch.'}]}),/MCP management/);}catch(error){error.message+=' '+JSON.stringify({pendingInitialize:owner.wire.pendingInitialize,receipt:await call('session.mcpActionStatus',{requestId:'held'}),info:await call('session.mcpInfo'),stats:owner.wire.stats});throw error;}
 owner.wire.releaseInitialize();row=await owner.settle(sid,'held');assert.equal(row.result,'registration-events-settled');assert(row.cancelRequested);assert.equal((await call('session.mcpInfo')).servers.find(row=>row.name==='header').enabled,true);assert.equal(owner.requests.length,0);
 let profile=await call('session.mcpProfile');await call('session.mcpConfigure',{requestId:'disable-for-interrupt',operation:'set-enabled',server:'header',enabled:false,expectedRevision:profile.revision});await owner.settle(sid,'disable-for-interrupt');
 owner.wire.holdInitialize();input=await configure('interrupted-config');await call('session.mcpConfigure',input);await until(async()=>owner.wire.pendingInitialize>0&&!!(await call('session.mcpActionStatus',{requestId:input.requestId})).savedRevision,'held initialization and saved interruptible profile');await owner.stop('SIGKILL');owner.wire.releaseInitialize();const stats=structuredClone(owner.wire.stats);await owner.start();row=await call('session.mcpActionStatus',{requestId:input.requestId});assert.equal(row.state,'interrupted');assert.equal(row.result,'unknown');assert(row.saveAttempted);assert(row.savedRevision);assert((await call('session.mcpConfigure',input)).duplicate);assert.deepEqual(owner.wire.stats,stats);assert.equal((await call('session.mcpInfo')).available,false);assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);
});

test('MCP profile changes reject a namespace owned by an approved extension before saving',{timeout:60000},async t=>{
 const owner=await managementOwner(t),sid=await owner.create();await owner.stop();const extension=join(owner.root,'authored-extension.mjs');await writeFile(extension,'export default pi=>pi.registerMcpServer("extension-owned",'+JSON.stringify({...owner.wire.config,enabled:false})+');');await writeFile(join(owner.config,'resources.json'),JSON.stringify({sources:[extension],skills:[]}));await owner.start();await owner.client.call('session.selectModel',{sessionId:sid,...owner.selection});await owner.client.call('events.subscribe',{sessionId:sid});const before=await owner.client.call('session.mcpProfile',{sessionId:sid}),document=JSON.parse(before.text);document.mcpServers.extension_owned={...owner.wire.config,enabled:false};await owner.client.call('session.mcpConfigure',{sessionId:sid,requestId:'conflict',operation:'save-profile',expectedRevision:before.revision,text:JSON.stringify(document)});const row=await owner.settle(sid,'conflict');assert.equal(row.result,'configuration-not-saved');assert.equal((await owner.client.call('session.mcpProfile',{sessionId:sid})).revision,before.revision);assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);
});
