// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
// Actual private owner/public SDK lifecycle, independently authored fixtures.
import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {managementOwner,until} from './fixtures/mcp-management-owner.mjs';
import {PiConnection} from '../dist/client/src/socket.js';
import {localConnect} from '../dist/platform/src/transport.js';

const rows=async file=>(await readFile(file,'utf8')).trim().split('\n').filter(Boolean).map(line=>JSON.parse(line));
async function save(owner,sid,requestId,edit){
 const before=await owner.client.call('session.mcpProfile',{sessionId:sid}),document=JSON.parse(before.text);edit(document);
 const input={sessionId:sid,requestId,operation:'save-profile',expectedRevision:before.revision,text:JSON.stringify(document)};
 await owner.client.call('session.mcpConfigure',input);return {input,receipt:await owner.settle(sid,requestId)};
}
const info=(owner,sid)=>owner.client.call('session.mcpInfo',{sessionId:sid});
const native=async(owner,sid)=>join(owner.state,'sessions',sid,(await readdir(join(owner.state,'sessions',sid))).find(name=>name.endsWith('.jsonl')));

test('public option reload changes actual logging/discovery and preserves original bytes, nested guards and one inspection hook per request',{timeout:90000},async t=>{
 const owner=await managementOwner(t);await owner.stop();
 const wireLog=join(owner.root,'authored-stdio.jsonl'),fixture=fileURLToPath(new URL('./fixtures/managed-mcp-server.mjs',import.meta.url));
 const profile=JSON.parse(await readFile(join(owner.agent,'mcp.json'),'utf8'));profile.mcpServers.script={command:process.execPath,args:[fixture,'--stdio','options',wireLog],exposure:'codemode',timeout:2};profile.augmentor.readOnlyTools.push('mcp__script__search_record');
 await writeFile(join(owner.agent,'mcp.json'),JSON.stringify(profile),{mode:0o600});
 const requests=[];let code='text(await tools.mcp__script__search_record({query:"authored-before-reload"}));';
 const provider=http.createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;requests.push(JSON.parse(raw));const first=requests.length%2===1,delta=first?{role:'assistant',tool_calls:[{index:0,id:'authored-option-call-'+requests.length,type:'function',function:{name:'codemode',arguments:JSON.stringify({code})}}]}:{role:'assistant',content:'Authored reload qualification complete.'};res.writeHead(200,{'content-type':'text/event-stream'}).end('data: '+JSON.stringify({id:'authored-options',choices:[{index:0,delta,finish_reason:first?'tool_calls':'stop'}]})+'\n\ndata: [DONE]\n\n');});provider.listen(0,'127.0.0.1');await once(provider,'listening');t.after(async()=>{provider.closeAllConnections();await new Promise(done=>provider.close(done));});
 const models=JSON.parse(await readFile(join(owner.agent,'models.json'),'utf8'));models.providers.fixture.baseUrl='http://127.0.0.1:'+provider.address().port+'/v1';await writeFile(join(owner.agent,'models.json'),JSON.stringify(models));
 await owner.start();const sid=await owner.create(),other=await owner.create('other');await owner.client.call('events.subscribe',{sessionId:sid});
 const ready=async()=>{for(const sessionId of [sid,other])if(!(await info(owner,sessionId)).servers.find(row=>row.name==='script')?.toolNames.includes('mcp__script__search_record'))return false;return true;};
 await until(ready,'actual stdio registrations');
 const run=async requestId=>{const before=requests.length;await owner.client.call('session.prompt',{sessionId:sid,requestId,content:[{type:'text',text:'Qualify the authored script once.'}]});await until(()=>owner.events.some(row=>row.method==='session/event'&&row.payload.event.type==='turn/end'&&row.payload.event.data?.requestId===requestId)||owner.events.filter(row=>row.method==='session/event'&&row.payload.event.type==='turn/end').length===requests.length/2&&requests.length===before+2,'explicit SDK turn');assert.equal(requests.length,before+2);};
 await run('before-reload');const file=await native(owner,sid),original=await readFile(file),pid=owner.owner.pid,selection=await owner.client.call('session.models',{sessionId:sid});
 for(const sessionId of [sid,other])await assert.rejects(readFile(join(owner.state,'mcp-logs',sessionId+'.log')),error=>error.code==='ENOENT');
 const enabled=await save(owner,sid,'logs-on',document=>{document.augmentor.retainServerLogs=true;});assert.equal(enabled.receipt.result,'session-options-applied');assert.equal(enabled.receipt.reloadedSessions,2);assert.equal(enabled.receipt.pendingSessionOptions,false);assert.equal(owner.owner.pid,pid);assert.deepEqual(await owner.client.call('session.models',{sessionId:sid}),selection);assert.deepEqual((await readFile(file)).subarray(0,original.length),original,'all original native bytes remain');
 await until(ready,'reloaded stdio catalog');for(const sessionId of [sid,other]){const catalog=await info(owner,sessionId);assert(catalog.retainServerLogs);assert(catalog.activeDiscoveryTools.includes('codemode'));await until(async()=>{try{return (await readFile(join(owner.state,'mcp-logs',sessionId+'.log'),'utf8')).includes('SYNTHETIC_SERVER_LOG');}catch{return false;}},'actual retained server log');}
 assert.equal(requests.length,2,'configuration does no inference');assert.equal((await rows(wireLog)).filter(row=>row.method==='tools/call').length,1,'configuration executes no tool');
 code='text(await tools.mcp__script__search_record({query:"authored-after-reload"}));';await run('after-reload');
 let originals=(await rows(file)).filter(row=>row.customType==='augmentor-tool-original/1');assert.equal(originals.filter(row=>row.data.parentToolCallId==='authored-option-call-3'&&row.data.toolName==='mcp__script__search_record').length,1,'nested evidence uses the new runner exactly once');
 const observed=await owner.client.call('observation.list',{sessionId:sid,limit:500});const serialized=JSON.stringify(observed);assert(serialized.includes('context/provenance'));const records=Array.isArray(observed)?observed:observed.records;assert.equal(records.filter(row=>row.kind==='model/request').length,requests.length,'one context inspector per actual provider request');assert.equal(records.filter(row=>row.kind==='execution/reasoning').length,requests.length,'one reasoning hook per actual provider request');
 code='text(await tools.mcp__script__write_record({nonce:"AUTHORED_MUST_NOT_WRITE"}));';await run('denied-after-reload');assert.equal((await rows(wireLog)).filter(row=>row.method==='tools/call'&&row.name==='write_record').length,0,'a misleading server read hint cannot bypass the new runner policy');assert.match(JSON.stringify(requests.at(-1).messages),/read-only|disabled|not approved/i);
 const disabled=await save(owner,sid,'logs-and-auto-off',document=>{document.augmentor.retainServerLogs=false;document.autoEnableCodemode=false;});assert.equal(disabled.receipt.reloadedSessions,2);assert.equal(disabled.receipt.result,'session-options-applied');await until(ready,'disabled logging reload');const retained=new Map();for(const sessionId of [sid,other]){const catalog=await info(owner,sessionId);assert.equal(catalog.retainServerLogs,false);assert(!catalog.activeDiscoveryTools.includes('codemode'),'log-only reload retains ownership of prior automatic activation');retained.set(sessionId,await readFile(join(owner.state,'mcp-logs',sessionId+'.log')));}
 // Reconnect starts a server that sends another logging notification; no old
 // retained log may grow after logging was disabled in that same conversation.
 await owner.client.call('session.mcpAction',{sessionId:sid,requestId:'disabled-log-reconnect',server:'script',action:'reconnect'});await owner.settle(sid,'disabled-log-reconnect');await until(ready,'explicit reconnect');
 for(const sessionId of [sid,other])assert.deepEqual(await readFile(join(owner.state,'mcp-logs',sessionId+'.log')),retained.get(sessionId));
 const before=requests.length;const enabledAgain=await save(owner,sid,'auto-on',document=>{document.autoEnableCodemode=true;});assert.equal(enabledAgain.receipt.result,'session-options-applied');for(const sessionId of [sid,other])assert((await info(owner,sessionId)).activeDiscoveryTools.includes('codemode'));assert.equal(requests.length,before);
 assert.deepEqual(owner.wire.errors,[]);
});

test('approved resource reload cannot start an unadmitted SDK prompt',{timeout:60000},async t=>{
 const owner=await managementOwner(t);await owner.stop();const extension=join(owner.root,'authored-unadmitted-input.mjs');
 await writeFile(extension,'export default pi=>{pi.on("session_start",event=>{if(event.reason==="reload")pi.sendUserMessage("AUTHORED_UNADMITTED_RELOAD_PROMPT");});};');await writeFile(join(owner.config,'resources.json'),JSON.stringify({sources:[extension],skills:[]}));await owner.start();const sid=await owner.create();
 const {receipt}=await save(owner,sid,'safe-resource-reload',document=>{document.augmentor.retainServerLogs=true;});assert.equal(receipt.result,'session-options-applied');assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);assert(!JSON.stringify(await owner.client.call('session.history',{sessionId:sid})).includes('AUTHORED_UNADMITTED_RELOAD_PROMPT'));assert.equal((await owner.client.call('session.queue',{sessionId:sid})).items.length,0);
});


test('an actual held Browser provider request excludes public option reload before any profile write or Native connection change',{timeout:60000},async t=>{
 const owner=await managementOwner(t),sid=await owner.create(),browser='authored-active-browser';await owner.client.call('session.create',{sessionId:browser,cwd:owner.cwd,selection:owner.selection,surface:'browser'});
 const socket=localConnect(join(owner.state,'runtime.sock'));await once(socket,'connect');const browserClient=new PiConnection(socket,event=>owner.events.push(event));t.after(()=>browserClient.close());await browserClient.call('host.hello',{protocol:'augmentor-pi/1'});await browserClient.call('events.subscribe',{sessionId:browser});
 owner.holdProvider();await owner.client.call('session.prompt',{sessionId:browser,requestId:'held-browser',content:[{type:'text',text:'Hold the authored provider.'}]});await until(()=>owner.pendingProvider===1,'actual admitted Browser provider request');
 const before=await owner.client.call('session.mcpProfile',{sessionId:sid}),stats=structuredClone(owner.wire.stats);const rejected=await save(owner,sid,'reject-active-browser',document=>{document.augmentor.retainServerLogs=true;});assert.equal(rejected.receipt.state,'failed');assert.equal(rejected.receipt.result,'configuration-not-saved');assert.equal(rejected.receipt.saveAttempted,undefined);assert.deepEqual(await owner.client.call('session.mcpProfile',{sessionId:sid}),before);assert.deepEqual(owner.wire.stats,stats);assert.equal((await info(owner,sid)).configuration.registrationPending,false);
 owner.releaseProvider();await until(()=>owner.events.some(row=>row.method==='session/event'&&row.payload.sessionId===browser&&row.payload.event.type==='turn/end'),'held Browser completion');
 const requests=owner.requests.length;const applied=await save(owner,sid,'idle-browser-options',document=>{document.augmentor.retainServerLogs=true;});assert.equal(applied.receipt.result,'session-options-applied');assert.equal(applied.receipt.reloadedSessions,1);assert.equal(owner.requests.length,requests,'idle option reload adds no provider request');assert.equal((await owner.client.call('session.mcpInfo',{sessionId:browser})).available,false,'Browser still grants no MCP authority');
});


test('held public reload keeps cancellation/Browser admission safe; a reported resource failure stays partial and an explicit retry repairs it',{timeout:90000},async t=>{
 const owner=await managementOwner(t);await owner.stop();const hold=join(owner.root,'hold-reload'),entered=join(owner.root,'entered-reload'),release=join(owner.root,'release-reload'),fail=join(owner.root,'fail-reload'),extension=join(owner.root,'authored-reload.mjs');
 await writeFile(extension,'import {existsSync,writeFileSync} from "node:fs";import {setTimeout as delay} from "node:timers/promises";export default pi=>{pi.on("session_shutdown",async event=>{if(event.reason!=="reload"||!existsSync('+JSON.stringify(hold)+'))return;writeFileSync('+JSON.stringify(entered)+',"entered");const deadline=Date.now()+10000;while(!existsSync('+JSON.stringify(release)+')&&Date.now()<deadline)await delay(25);if(!existsSync('+JSON.stringify(release)+'))throw Error("AUTHORED_RELOAD_HOLD_TIMEOUT");});pi.on("session_start",event=>{if(event.reason!=="reload")pi.setActiveTools([...new Set([...pi.getActiveTools(),"codemode"])]);if(event.reason==="reload"&&existsSync('+JSON.stringify(fail)+'))throw Error("AUTHORED_PRIVATE_RELOAD_ERROR");});};');
 await writeFile(join(owner.config,'resources.json'),JSON.stringify({sources:[extension],skills:[]}));await owner.start();const sid=await owner.create(),browser='authored-browser';await owner.client.call('session.create',{sessionId:browser,cwd:owner.cwd,selection:owner.selection,surface:'browser'});
 await owner.client.call('session.cancel',{sessionId:sid});assert.equal((await owner.client.call('session.queue',{sessionId:sid})).paused,true);
 await owner.client.call('session.prompt',{sessionId:sid,requestId:'paused-input',mode:'queue',resumeQueue:false,content:[{type:'text',text:'Keep this waiting prompt paused.'}]});
 await writeFile(hold,'hold');const before=await owner.client.call('session.mcpProfile',{sessionId:sid}),document=JSON.parse(before.text);document.autoEnableCodemode=false;const input={sessionId:sid,requestId:'held-options',operation:'save-profile',expectedRevision:before.revision,text:JSON.stringify(document)};await owner.client.call('session.mcpConfigure',input);
 await until(async()=>{try{return (await readFile(entered,'utf8'))==='entered'&&(await owner.client.call('session.mcpActionStatus',{sessionId:sid,requestId:'held-options'})).savedRevision;}catch{return false;}},'actual public shutdown hold after save');
 const heldSnapshot=await owner.client.call('session.mcpActionStatus',{sessionId:sid,requestId:'held-options',includeCatalog:true});assert.equal(heldSnapshot.state,'running');assert.equal(heldSnapshot.catalog.management.lastReceipt.state,heldSnapshot.state);assert(heldSnapshot.catalog.configuration.pendingSessionOptions);
 await owner.client.call('session.mcpCancelAction',{sessionId:sid,requestId:'held-options'});assert((await info(owner,sid)).management.busy);for(const method of ['session.prompt','session.continueQueue','session.selectModel'])await assert.rejects(owner.client.call(method,{sessionId:browser,requestId:'must-wait',content:[{type:'text',text:'Do not run.'}],...owner.selection}),/MCP session reload/);
 assert.equal(owner.requests.length,0);await writeFile(release,'release');const completed=await owner.settle(sid,'held-options');assert.equal(completed.result,'session-options-applied');assert(completed.cancelRequested);assert((await info(owner,sid)).activeDiscoveryTools.includes('codemode'),'an explicit extension activation is preserved when automatic activation is disabled');const waiting=await owner.client.call('session.queue',{sessionId:sid});assert(waiting.paused);assert(waiting.items.some(row=>row.id==='paused-input'));assert.equal(owner.requests.length,0);
 const settledSnapshot=await owner.client.call('session.mcpActionStatus',{sessionId:sid,requestId:'held-options',includeCatalog:true});assert.equal(settledSnapshot.state,'completed');assert.equal(settledSnapshot.catalog.management.lastReceipt.state,settledSnapshot.state);assert.equal(settledSnapshot.catalog.configuration.pendingSessionOptions,false);assert.equal(settledSnapshot.catalog.management.busy,false);
 await writeFile(fail,'fail');const broken=await save(owner,sid,'broken-options',value=>{value.augmentor.retainServerLogs=true;});assert.equal(broken.receipt.state,'failed');assert.equal(broken.receipt.result,'profile-saved-partial');assert((await info(owner,sid)).configuration.pendingSessionOptions);const partialQueue=await owner.client.call('session.queue',{sessionId:sid});await assert.rejects(owner.client.call('session.prompt',{sessionId:sid,requestId:'must-refuse-partial',content:[{type:'text',text:'Do not run.'}]}),/configuration has not settled/);assert.deepEqual(await owner.client.call('session.queue',{sessionId:sid}),partialQueue,'Refusing a partial-configuration prompt must not create a waiting receipt');await assert.rejects(owner.client.call('session.prompt',{sessionId:sid,requestId:'must-refuse-partial-queue',mode:'queue',resumeQueue:false,content:[{type:'text',text:'Do not queue.'}]}),/configuration has not settled/);await assert.rejects(owner.client.call('session.continueQueue',{sessionId:sid}),/configuration has not settled/);assert.deepEqual(await owner.client.call('session.queue',{sessionId:sid}),partialQueue);assert(!JSON.stringify(owner.events).includes('AUTHORED_PRIVATE_RELOAD_ERROR'));assert(!JSON.stringify(broken.receipt).includes('AUTHORED_PRIVATE_RELOAD_ERROR'));
 const {unlink}=await import('node:fs/promises');await unlink(fail);const repaired=await save(owner,sid,'repair-options',()=>{});assert.equal(repaired.receipt.result,'session-options-applied');assert.equal(repaired.receipt.pendingSessionOptions,false);assert.equal((await info(owner,sid)).configuration.registrationPending,false);assert.equal(owner.requests.length,0);assert.equal((await owner.client.call('session.queue',{sessionId:sid})).paused,true);
});
