// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {join} from 'node:path';
import {managementOwner,until} from './fixtures/mcp-management-owner.mjs';
test('actual Pi owner manages PKCE login, rotated refresh tokens, sign-out and private receipts without inference or action replay',{timeout:90000},async t=>{
 const owner=await managementOwner(t),sid=await owner.create(),call=(method,params={})=>owner.client.call(method,{sessionId:sid,...params});
 const info=await call('session.mcpInfo');assert(info.management.available);assert.deepEqual(info.servers.find(row=>row.name==='web').managementActions,['login','logout','reconnect']);assert.deepEqual(info.servers.find(row=>row.name==='disabled').managementActions,[]);assert.equal(owner.requests.length,0);assert(!JSON.stringify(info).includes(owner.wire.base));
 await assert.rejects(call('session.mcpAction',{requestId:'disabled',server:'disabled',action:'reconnect'}),/enabled/);await assert.rejects(call('session.mcpAction',{requestId:'invalid',server:'web',action:'other'}),/Choose/);
 const login={requestId:'login',server:'web',action:'login'};await call('session.mcpAction',login);let row;await until(async()=>{row=await call('session.mcpActionStatus',{requestId:'login'});return !!row.authorizationUrl;},'sign-in URL');assert.equal((await call('session.mcpAction',login)).duplicate,true);assert.equal(owner.requests.length,0);
 await assert.rejects(call('session.prompt',{requestId:'must-not-send',content:[{type:'text',text:'MUST_NOT_SEND_DURING_AUTH'}]}),/MCP management/);await assert.rejects(call('session.mcpAction',{requestId:'other',server:'web',action:'logout'}),/active/);await assert.rejects(owner.client.call('session.mcpActionStatus',{sessionId:'foreign',requestId:'login'}),/Conversation not found/);
 const inspect=await owner.client.call('inspection.open',{sessionId:sid}),url=new URL(inspect.url),token=new URLSearchParams(url.hash.slice(1)).get('token');for(const method of ['session.mcpAction','session.mcpActionStatus','session.mcpCancelAction','session.mcpSubmitRedirect']){const response=await fetch(url.origin+'/api/rpc',{method:'POST',headers:{Authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({id:'inspection',method,params:{sessionId:sid,...login}})});assert.equal(response.status,400,method);}
 const receiptText=await readFile(join(owner.state,'mcp-management.json'),'utf8');assert(!receiptText.includes('state='));assert(!JSON.stringify(owner.events).includes(row.authorizationUrl));
 row=await owner.authorize(sid,'login');assert.equal(row.state,'completed',owner.errors);assert.equal(row.result,'sdk-reported-success');assert.equal(row.authorizationUrl,null);assert.equal(owner.wire.stats.pkceVerified,1);assert.equal(owner.wire.stats.codeGrants,1);assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);
 const authFile=join(owner.agent,'mcp-auth.json');let credentials=await readFile(authFile,'utf8');assert(credentials.includes('AUTHORED_ACCESS_1'));assert(credentials.includes('AUTHORED_REFRESH_1'));assert.equal((await stat(authFile)).mode&0o777,0o600);
 owner.wire.rejectToken();await call('session.mcpAction',{requestId:'refresh',server:'web',action:'reconnect'});row=await owner.settle(sid,'refresh');assert.equal(row.result,'sdk-reported-success',JSON.stringify({receipt:row,stats:owner.wire.stats,wireErrors:owner.wire.errors,rotatedAccessSaved:(await readFile(authFile,'utf8')).includes('AUTHORED_ACCESS_2'),ownerError:owner.errors}));assert.equal(owner.wire.stats.refreshGrants,1);credentials=await readFile(authFile,'utf8');assert(credentials.includes('AUTHORED_ACCESS_2'));assert(credentials.includes('AUTHORED_REFRESH_2'));assert(!credentials.includes('AUTHORED_REFRESH_1'));assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);
 await owner.stop();await owner.start();const before={...owner.wire.stats};assert.equal((await call('session.mcpInfo')).available,false);assert.equal((await call('session.mcpAction',login)).duplicate,true);assert.deepEqual(owner.wire.stats,before);assert.equal(owner.requests.length,0);assert.equal((await call('session.mcpActionStatus',{requestId:'refresh'})).result,'sdk-reported-success');
 await call('session.selectModel',{provider:owner.selection.provider,model:owner.selection.model});await call('events.subscribe');await until(async()=>{const info=await call('session.mcpInfo');return info.servers.find(row=>row.name==='web').toolCount===1;},'restored credential connection');assert.equal(owner.wire.stats.codeGrants,1);assert.equal(owner.wire.stats.refreshGrants,1);
 await call('session.prompt',{requestId:'explicit-read',content:[{type:'text',text:'Read the authored record once.'}]});await until(()=>owner.events.some(frame=>frame.method==='session/event'&&frame.payload.event.type==='turn/end'),'explicit read');assert.equal(owner.wire.stats.tools,1);assert.equal(owner.requests.length,2);
 await call('session.mcpAction',{requestId:'logout',server:'web',action:'logout'});row=await owner.settle(sid,'logout');assert.equal(row.result,'sdk-reported-success');credentials=await readFile(authFile,'utf8');assert(!credentials.includes('AUTHORED_ACCESS_2'));assert(!credentials.includes('AUTHORED_REFRESH_2'));
 const history=JSON.stringify(await call('session.history',{maxMessages:100})),observations=JSON.stringify(await owner.client.call('observation.list',{sessionId:sid,limit:500})),receipts=await readFile(join(owner.state,'mcp-management.json'),'utf8');for(const text of [history,observations,receipts])for(const secret of ['AUTHORED_ACCESS_','AUTHORED_REFRESH_','AUTHORED_CODE_','code_challenge=','AUTHORED_PRIVATE_REFRESH_ERROR'])assert(!text.includes(secret),'management evidence excludes credentials');assert.equal(owner.requests.length,2);assert.deepEqual(owner.wire.errors,[]);assert.equal(existsSync(join(owner.home,'.pi','agent')),false);assert((await readFile(owner.network,'utf8')).trim().split('\n').filter(Boolean).every(line=>JSON.parse(line).allowed));
});
test('actual SDK validates pasted redirect state and cancellation before the authorization prompt',{timeout:60000},async t=>{
 const owner=await managementOwner(t),sid=await owner.create(),call=(method,params={})=>owner.client.call(method,{sessionId:sid,...params});
 owner.wire.holdMetadata();await call('session.mcpAction',{requestId:'early-cancel',server:'web',action:'login'});await call('session.mcpCancelAction',{requestId:'early-cancel'});assert.equal((await call('session.mcpActionStatus',{requestId:'early-cancel'})).state,'cancel-requested');await assert.rejects(call('session.mcpAction',{requestId:'must-wait',server:'web',action:'reconnect'}),/active/);owner.wire.releaseMetadata();let row=await owner.settle(sid,'early-cancel');assert.equal(row.state,'cancelled');assert.equal(owner.wire.stats.codeGrants,0);
 for(const [requestId,wrong] of [['wrong-state',true],['pasted-login',false]]){
  await call('session.mcpAction',{requestId,server:'web',action:'login'});await until(async()=>{row=await call('session.mcpActionStatus',{requestId});return row.authorizationUrl&&row.waitingForRedirect;},'paste-ready sign-in');const response=await fetch(row.authorizationUrl,{redirect:'manual'}),redirect=new URL(response.headers.get('location'));if(wrong)redirect.searchParams.set('state','AUTHORED_WRONG_STATE');await call('session.mcpSubmitRedirect',{requestId,url:redirect.href});row=await owner.settle(sid,requestId);assert.equal(row.state,wrong?'failed':'completed');assert.equal(row.result,wrong?'sdk-reported-error':'sdk-reported-success');assert.equal(row.authorizationUrl,null);assert.equal(row.waitingForRedirect,false);
 }
 assert.equal(owner.wire.stats.pkceVerified,1);assert.equal(owner.wire.stats.codeGrants,1);assert.equal(owner.requests.length,0);assert.equal(owner.wire.stats.tools,0);const evidence=JSON.stringify(owner.events)+await readFile(join(owner.state,'mcp-management.json'),'utf8');assert(!evidence.includes('AUTHORED_WRONG_STATE'));assert(!evidence.includes('AUTHORED_CODE_'));assert.deepEqual(owner.wire.errors,[]);
});
test('actual SDK cancellation and interrupted management recover without replay',{timeout:60000},async t=>{
 const owner=await managementOwner(t),sid=await owner.create(),call=(method,params={})=>owner.client.call(method,{sessionId:sid,...params});
 await call('session.mcpAction',{requestId:'cancel-login',server:'web',action:'login'});await until(async()=>!!(await call('session.mcpActionStatus',{requestId:'cancel-login'})).authorizationUrl,'cancellable sign-in');const stop=await call('session.cancel');assert.equal(stop.accepted,true);assert.equal(stop.paused,true);let row=await owner.settle(sid,'cancel-login');assert(row.cancelRequested);assert.equal(row.state,'cancelled');assert.equal(row.authorizationUrl,null);assert.equal(owner.wire.stats.codeGrants,0);assert.equal(owner.requests.length,0);
 await call('session.mcpAction',{requestId:'interrupted-login',server:'web',action:'login'});await until(async()=>!!(await call('session.mcpActionStatus',{requestId:'interrupted-login'})).authorizationUrl,'interruptible sign-in');await owner.stop('SIGKILL');await owner.start();row=await call('session.mcpActionStatus',{requestId:'interrupted-login'});assert.equal(row.state,'interrupted');assert.equal(row.result,'unknown');assert.equal(row.authorizationUrl,null);assert.equal((await call('session.mcpAction',{requestId:'interrupted-login',server:'web',action:'login'})).duplicate,true);assert.equal(owner.wire.stats.codeGrants,0);assert.equal(owner.wire.stats.tools,0);assert.equal(owner.requests.length,0);assert.deepEqual(owner.wire.errors,[]);assert.equal(existsSync(join(owner.home,'.pi','agent')),false);
});
