// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {once} from 'node:events';
import {readFile,access,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {PiPromptImprovement} from '../dist/runtime/src/prompt-improvement.js';
import {PiConnection} from '../dist/client/src/socket.js';
import {localConnect} from '../dist/platform/src/transport.js';
async function until(fn){const end=Date.now()+10000;while(Date.now()<end){if(await fn())return;await delay(20);}throw Error('Pi improvement fixture timeout');}
test('real Pi draft transactions are tool-free, isolated, cancellable and never replay unknown outcomes',{timeout:45000},async t=>{
  const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!/^(AUGMENTOR_|DSH_|PI_)/.test(key)));for(const key of ['AUGMENTOR_PI_TEST_ROOT','AUGMENTOR_PYTHON'])if(process.env[key])env[key]=process.env[key];
  const child=spawn(process.execPath,['scripts/harness-ui-proof.mjs'],{env:{...env,AUGMENTOR_HARNESS_PROOF_RECORD_REQUESTS:'1',AUGMENTOR_HARNESS_PROOF_PROMPTS:'1'},stdio:['ignore','pipe','pipe']});let output='',stderr='',link;
  child.stdout.on('data',data=>output+=data);child.stderr.on('data',data=>stderr+=data);
  t.after(async()=>{if(child.exitCode===null){const ended=once(child,'exit');child.kill('SIGTERM');await ended;}});
  await until(()=>{if(child.exitCode!==null)throw Error(stderr);try{link=JSON.parse(output.trim().split('\n').find(line=>line.startsWith('{"fixture"')));return !!link;}catch{return false;}});
  const url=new URL(link.url),token=new URLSearchParams(url.hash.slice(1)).get('token');
  const socket=localConnect(join(link.state,'runtime.sock'));await once(socket,'connect');const owner=new PiConnection(socket);await owner.call('host.hello',{protocol:'augmentor-pi/1'});t.after(()=>owner.close());
  const rpc=async(method,params={})=>{const response=await fetch(url.origin+'/api/rpc',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),method,params})}),frame=await response.json();if(frame.error)throw Error(frame.error.message);return frame.result;};
  const requests=async()=>{try{return (await readFile(link.requestLog,'utf8')).trim().split('\n').filter(Boolean).map(line=>JSON.parse(line));}catch{return [];}};
  const selection={provider:'fixture',model:'harness-fixture'},sessionId='draft-parent';
  await writeFile(join(link.workspace,'AGENTS.md'),'PRIVATE_PROJECT_INSTRUCTION_FIXTURE\n');
  await rpc('session.create',{sessionId,selection,cwd:link.workspace});
  const observationsBefore=await rpc('observation.list',{sessionId}),before=await rpc('session.history',{sessionId}),revision=(await rpc('prompts.list')).improvement.revision;
  const params=(text,requestId=crypto.randomUUID())=>({sessionId,scopeId:'editor',selection,text,requestId,expectedInstructionsRevision:revision});
  const one=params('Original café draft'),result=await rpc('prompt.improve',one).catch(async error=>{error.message+=' '+JSON.stringify({status:await rpc('prompt.improvementStatus',{requestId:one.requestId}),requests:await requests(),stderr});throw error;});
  assert.equal(result.text,'Improved Original café draft');assert.equal(result.receipt.status,'completed');assert.equal(result.receipt.usage.output,12);
  assert.equal((await requests()).length,1);const body=(await requests())[0];
  assert.equal(body.model,selection.model);assert.equal(body.tools?.length??0,0);assert.equal(body.messages.filter(m=>m.role==='user').length,1);
  assert.doesNotMatch(JSON.stringify(body),/PRIVATE_PROJECT_INSTRUCTION_FIXTURE|memory_source|augmentor_memory_manifest|browser_snapshot|\[clipboard\]/);
  assert.match(JSON.stringify(body),/Inline editor override/);
  assert.doesNotMatch(JSON.stringify(body),/<cwd>/);assert(!JSON.stringify(body).includes(link.state));assert(!JSON.stringify(body).includes(link.workspace));assert.equal(result.receipt.effectiveModel,selection.model);
  assert.deepEqual((await rpc('session.history',{sessionId})),before);
  assert.deepEqual(await rpc('observation.list',{sessionId}),observationsBefore);
  const receipt=(await rpc('prompt.improvementStatus',{requestId:one.requestId}));assert.equal(receipt.payloadsRetained,false);assert.equal(receipt.receipt.requests,1);
  await assert.rejects(rpc('prompt.improve',one),/not replayed/);assert.equal((await requests()).length,1);
  for(const text of ['IMPROVE_INVALID','IMPROVE_TOOL','IMPROVE_TRUNCATED']){const p=params(text),n=(await requests()).length;await assert.rejects(rpc('prompt.improve',p),/valid rewrite/);assert.equal((await requests()).length,n+1);assert.equal((await rpc('prompt.improvementStatus',{requestId:p.requestId})).receipt.status,'failed');}
  await assert.rejects(access(join(link.workspace,'must-not-exist')));
  const cancelled=params('never submitted');await rpc('prompt.cancelImprovement',{requestId:cancelled.requestId,scopeId:cancelled.scopeId});const count=(await requests()).length;await assert.rejects(rpc('prompt.improve',cancelled),/not replayed/);assert.equal((await requests()).length,count);
  const slow=params('IMPROVE_SLOW'),pending=rpc('prompt.improve',slow),rejected=assert.rejects(pending,/interrupted/);
  await until(async()=>(await requests()).length===count+1);
  await assert.rejects(rpc('host.prepareShutdown'),/not exposed/);
  await assert.rejects(owner.call('host.prepareShutdown'),/cancel prompt improvement/);
  await assert.rejects(owner.call('models.reload'),/cancel prompt improvement/);
  await assert.rejects(rpc('session.prompt',{sessionId,requestId:'chat-while-improving',content:[{type:'text',text:'Not authorized yet'}]}),/cancel prompt improvement/);
  const duplicate=assert.rejects(rpc('prompt.improve',slow),/interrupted|not replayed/);await rpc('prompt.cancelImprovement',{requestId:slow.requestId,scopeId:slow.scopeId});await Promise.all([rejected,duplicate]);assert.equal((await requests()).length,count+1);
  await assert.rejects(rpc('prompt.improve',slow),/not replayed/);
  assert.deepEqual(await rpc('session.history',{sessionId}),before);
  const saved=(await rpc('prompts.list')).improvement;await rpc('prompts.improvementSave',{content:'New saved instructions',expectedRevision:saved.revision});
  await assert.rejects(rpc('prompt.improve',params('stale settings')),/instructions changed/);assert.equal((await requests()).length,count+1);
  const restored=new PiPromptImprovement(join(link.state,'prompt-improvements.json'));assert.equal(restored.status(one.requestId).receipt.status,'completed');assert.equal(restored.status(slow.requestId).receipt.status,'cancelled');
  const persisted=await readFile(join(link.state,'prompt-improvements.json'),'utf8');assert.doesNotMatch(persisted,/Original café|Improved|New saved instructions|synthetic-not-a-real-key/);
  const python=process.env.AUGMENTOR_PYTHON??'python3';
  const native=await promisify(execFile)(python,['tests/fixtures/native-pi-improvement.py'],{env:{...env,HOME:link.home,XDG_CONFIG_HOME:join(link.home,'config'),XDG_STATE_HOME:join(link.home,'state'),XDG_DATA_HOME:join(link.home,'data'),XDG_CACHE_HOME:join(link.home,'cache'),AUGMENTOR_WORKSPACE_PROFILE:'',AUGMENTOR_PI_CONFIG:link.config,AUGMENTOR_PI_STATE:link.state,AUGMENTOR_PI_NO_AUTOSTART:'1',AUGMENTOR_SHARED_STATE:link.sharedState,AUGMENTOR_SHARED_DATA:link.sharedData,PYTHONPATH:join(process.env.AUGMENTOR_PI_TEST_ROOT??'.','apps/native'),QT_QPA_PLATFORM:'offscreen'},timeout:20000});
  assert.equal(JSON.parse(native.stdout).nativeImprovement,'passed');
});
