# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]/'services'))


@unittest.skipUnless(sys.platform == 'win32', 'requires the Windows token and ACL APIs')
class WindowsIdentityTests(unittest.TestCase):
    def test_current_process_identity_comes_from_the_os_token(self):
        from platform_adapters.windows_identity import current_sid, process_sid
        self.assertEqual(process_sid(os.getpid()), current_sid())

    def test_private_path_owner_permissions_and_reopen(self):
        from platform_adapters.windows_identity import private_directory, require_private_directory, current_sid
        import win32security
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary)/'Augmentor café'/'private'
            self.assertEqual(private_directory(path), path)
            self.assertEqual(private_directory(path), path)
            descriptor = win32security.GetFileSecurity(str(path), win32security.OWNER_SECURITY_INFORMATION)
            self.assertEqual(descriptor.GetSecurityDescriptorOwner(), current_sid())
            (path/'settings.json').write_text('{"selected":"kept"}')
            require_private_directory(path)
            self.assertEqual((path/'settings.json').read_text(), '{"selected":"kept"}')

    def test_permissive_existing_directory_is_refused_without_rewriting_acl(self):
        from platform_adapters.windows_identity import private_directory
        import win32security
        with tempfile.TemporaryDirectory() as temporary:
            path = private_directory(Path(temporary)/'private')
            descriptor = win32security.ConvertStringSecurityDescriptorToSecurityDescriptor(
                'D:P(A;OICI;FA;;;WD)', win32security.SDDL_REVISION_1)
            win32security.SetFileSecurity(str(path), win32security.DACL_SECURITY_INFORMATION, descriptor)
            before = win32security.GetFileSecurity(str(path), win32security.DACL_SECURITY_INFORMATION)
            with self.assertRaises(PermissionError):
                private_directory(path)
            after = win32security.GetFileSecurity(str(path), win32security.DACL_SECURITY_INFORMATION)
            stringify = lambda sd: win32security.ConvertSecurityDescriptorToStringSecurityDescriptor(
                sd, win32security.SDDL_REVISION_1, win32security.DACL_SECURITY_INFORMATION)
            self.assertEqual(stringify(before), stringify(after))

    def test_junction_cannot_redirect_private_state(self):
        from platform_adapters.windows_identity import private_directory
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            target = root/'target'; target.mkdir()
            link = root/'junction'
            # mklink is cmd's builtin; paths are generated by this fixture.
            subprocess.run(f'cmd.exe /d /s /c "mklink /J "{link}" "{target}""',
                           check=True, capture_output=True)
            try:
                with self.assertRaises(PermissionError):
                    private_directory(link/'private')
                self.assertFalse((target/'private').exists())
            finally:
                os.rmdir(link)


if __name__ == '__main__':
    unittest.main()
