# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]/'services'))


@unittest.skipUnless(sys.platform == 'win32', 'requires the Windows token and ACL APIs')
class WindowsIdentityTests(unittest.TestCase):
    def test_current_process_identity_comes_from_the_os_token(self):
        from platform_adapters.windows_identity import current_sid, process_sid
        self.assertEqual(process_sid(os.getpid()), current_sid())

    def test_private_lease_refuses_hard_link_and_reopens_without_truncating(self):
        from platform_adapters.windows_identity import private_directory, private_lock_descriptor
        with tempfile.TemporaryDirectory() as temporary:
            root = private_directory(Path(temporary)/'private')
            path = root/'installation.lock'
            descriptor = private_lock_descriptor(path)
            os.write(descriptor, b'kept')
            os.close(descriptor)
            descriptor = private_lock_descriptor(path)
            self.assertEqual(os.read(descriptor, 4), b'kept')
            os.close(descriptor)
            os.link(path, root/'other.lock')
            with self.assertRaises(PermissionError):
                private_lock_descriptor(path)

    def test_private_path_owner_permissions_and_reopen(self):
        from platform_adapters.windows_identity import private_directory, require_private_directory, current_sid
        import win32security
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary)/'Augmentor café'/'private'
            self.assertEqual(private_directory(path), path)
            self.assertEqual(private_directory(path), path)
            descriptor = win32security.GetFileSecurity(str(path), win32security.OWNER_SECURITY_INFORMATION)
            self.assertEqual(descriptor.GetSecurityDescriptorOwner(), current_sid())
            (path/'settings.json').write_text('{"selected":"kept"}')
            require_private_directory(path)
            self.assertEqual((path/'settings.json').read_text(), '{"selected":"kept"}')

    def test_permissive_existing_directory_is_refused_without_rewriting_acl(self):
        from platform_adapters.windows_identity import private_directory
        import win32security
        with tempfile.TemporaryDirectory() as temporary:
            path = private_directory(Path(temporary)/'private')
            descriptor = win32security.ConvertStringSecurityDescriptorToSecurityDescriptor(
                'D:P(A;OICI;FA;;;WD)', win32security.SDDL_REVISION_1)
            win32security.SetFileSecurity(str(path), win32security.DACL_SECURITY_INFORMATION, descriptor)
            before = win32security.GetFileSecurity(str(path), win32security.DACL_SECURITY_INFORMATION)
            with self.assertRaises(PermissionError):
                private_directory(path)
            after = win32security.GetFileSecurity(str(path), win32security.DACL_SECURITY_INFORMATION)
            stringify = lambda sd: win32security.ConvertSecurityDescriptorToStringSecurityDescriptor(
                sd, win32security.SDDL_REVISION_1, win32security.DACL_SECURITY_INFORMATION)
            self.assertEqual(stringify(before), stringify(after))

    def test_junction_cannot_redirect_private_state(self):
        from platform_adapters.windows_identity import private_directory
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            target = root/'target'; target.mkdir()
            link = root/'junction'
            # mklink is cmd's builtin; paths are generated by this fixture.
            subprocess.run(f'cmd.exe /d /s /c "mklink /J "{link}" "{target}""',
                           check=True, capture_output=True)
            try:
                with self.assertRaises(PermissionError):
                    private_directory(link/'private')
                self.assertFalse((target/'private').exists())
            finally:
                os.rmdir(link)

    def test_node_download_inherits_only_private_grants_then_receives_protected_acl(self):
        from platform_adapters.windows_identity import private_directory,protect_inherited_download,private_file_descriptor
        import shutil
        root=Path(__file__).resolve().parents[1]
        candidate=root/'outputs/payload/node/node.exe'
        node=str(candidate) if candidate.is_file() else shutil.which('node')
        if not node:self.skipTest('The qualified Node runtime is required for the download ACL proof.')
        with tempfile.TemporaryDirectory() as temporary:
            folder=private_directory(Path(temporary)/'private');file=folder/'download'
            subprocess.run([node,'-e',"require('node:fs').writeFileSync(process.argv[1],'fixture')",str(file)],check=True)
            protect_inherited_download(file)
            fd=private_file_descriptor(file)
            try:self.assertEqual(os.read(fd,7),b'fixture')
            finally:os.close(fd)
            os.link(file,folder/'alias')
            with self.assertRaises(PermissionError):protect_inherited_download(file)

    def test_download_sealing_refuses_public_grants_without_repairing_them(self):
        from platform_adapters.windows_identity import private_directory,protect_inherited_download
        import win32security
        with tempfile.TemporaryDirectory() as temporary:
            folder=private_directory(Path(temporary)/'private');file=folder/'public-download'
            file.write_bytes(b'preserved')
            descriptor=win32security.ConvertStringSecurityDescriptorToSecurityDescriptor(
                'D:P(A;;FA;;;WD)',win32security.SDDL_REVISION_1)
            win32security.SetFileSecurity(str(file),win32security.DACL_SECURITY_INFORMATION,descriptor)
            stringify=lambda:win32security.ConvertSecurityDescriptorToStringSecurityDescriptor(
                win32security.GetFileSecurity(str(file),win32security.DACL_SECURITY_INFORMATION),
                win32security.SDDL_REVISION_1,win32security.DACL_SECURITY_INFORMATION)
            before=stringify()
            with self.assertRaises(PermissionError):protect_inherited_download(file)
            self.assertEqual(stringify(),before);self.assertEqual(file.read_bytes(),b'preserved')


if __name__ == '__main__':
    unittest.main()
