// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
// Generated by scripts/sync-version.py.
export const RELEASE = {
  "version": "0.2.10",
  "channel": "preview",
  "protocols": {
    "product": "augmentor/1",
    "pi": "augmentor-pi/1",
    "prompts": "augmentor-prompts/1",
    "memory": "augmentor-memory/1",
    "desktop": "augmentor-desktop/1"
  },
  "dataSchema": 1,
  "readableDataSchemas": [
    1
  ]
} as const;
