# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
# ONLY for the expendable acceptance VM, with no personal files or credentials.
[Autologin]
User=beta
Session=plasma.desktop
Relogin=true
