#!/usr/bin/env python3
# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
"""Generate component versions from the single product release manifest."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
product = json.loads((ROOT / 'release/product.json').read_text())
version = product['version']
files = {}
for name in ('package.json', 'package-lock.json', 'apps/browser/package.json',
             'apps/browser/package-lock.json', 'apps/browser/plugin/package.json',
             'apps/browser/extension/manifest.json', 'adapters/dsh-prompt-library/package.json'):
    value = json.loads((ROOT / name).read_text())
    value['version'] = version
    if 'packages' in value:
        value['packages']['']['version'] = version
    files[name] = json.dumps(value, indent=2, ensure_ascii=False) + '\n'
files['packages/contracts/src/release.ts'] = '// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0\n// Generated by scripts/sync-version.py.\nexport const RELEASE = ' + json.dumps(product, indent=2) + ' as const;\n'
files['apps/native/augmentor_linux/__init__.py'] = '# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0\n# Generated by scripts/sync-version.py.\n__version__ = ' + json.dumps(version) + '\n'
changed = [name for name, text in files.items() if not (ROOT / name).exists() or (ROOT / name).read_text() != text]
if args.check and changed:
    raise SystemExit('Generated release versions differ: ' + ', '.join(changed))
if not args.check:
    for name in changed:
        (ROOT / name).write_text(files[name])
