#!/usr/bin/env python3
# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
"""Generate native and browser assets from the shared design source."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1];source=root/'packages/design'
values=json.loads((source/'actions.json').read_text())
for name in ('copy','check','edit','branch'):
 (root/'apps/native/augmentor_linux/assets'/f'{name}.svg').write_bytes((source/f'{name}.svg').read_bytes())
header='// Augmentor — dsh-augmentor plugin, pipe, and Chromium extension\n// Copyright © 2026 Manolo Remiddi\n// SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0\n// License: MIT with Augmentor Resale Restriction — see LICENSE at the repository root.\n// Generated by scripts/sync-design.py.\n'
output=header+'export const ACTIONS='+json.dumps(values)+';\n'
for name in ('copy','check','edit','branch'):output+='export const '+name.upper()+'_ICON='+json.dumps((source/f'{name}.svg').read_text())+';\n'
(root/'apps/browser/extension/action-design.mjs').write_text(output)
(root/'apps/native/augmentor_linux/design.py').write_text('# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0\n# Generated by scripts/sync-design.py.\nACTION_ICON_SIZE='+str(values['iconSize'])+'\nCOPY_FEEDBACK_MS='+str(values['copyFeedbackMs'])+'\nACTION_LABELS='+repr(values['labels'])+'\n')

(root/'apps/browser/extension/clipboard.mjs').write_text(header+(root/'packages/templates/clipboard.mjs').read_text())

# The native window and sidebar have one maintained geometry/icon contract.
surface=json.loads((source/'surface.json').read_text())
(root/'apps/native/augmentor_linux/surface_design.py').write_text('# Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0\n# Generated by scripts/sync-design.py.\nSURFACE='+repr(surface)+'\n')
(root/'apps/browser/extension/surface-design.mjs').write_text(header+'export const SURFACE='+json.dumps(surface,ensure_ascii=False)+';\n')
css='/* Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0\n * Generated by scripts/sync-design.py. */\n:root {\n'
for key,value in surface.items():
 if isinstance(value,int):css+='  --surface-'+key+': '+str(value)+'px;\n'
(root/'apps/browser/extension/surface-tokens.css').write_text(css+'}\n')
